# Generated by Django 4.2 on 2023-04-22 01:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import mptt.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="MailingListMessage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("message_id", models.CharField(max_length=255, unique=True)),
                (
                    "sender_email",
                    models.EmailField(
                        blank=True,
                        help_text="The email address of the sender.",
                        max_length=254,
                        null=True,
                    ),
                ),
                (
                    "sender_display",
                    models.CharField(
                        blank=True,
                        help_text="The display name of the sender.",
                        max_length=255,
                        null=True,
                    ),
                ),
                (
                    "subject",
                    models.CharField(
                        help_text="The subject of the message.", max_length=255
                    ),
                ),
                ("body", models.TextField(help_text="The body of the message.")),
                (
                    "sent_at",
                    models.DateTimeField(
                        help_text="The date and time when the message was sent."
                    ),
                ),
                (
                    "data",
                    models.JSONField(default=dict, help_text="The raw message data."),
                ),
                ("lft", models.PositiveIntegerField(editable=False)),
                ("rght", models.PositiveIntegerField(editable=False)),
                ("tree_id", models.PositiveIntegerField(db_index=True, editable=False)),
                ("level", models.PositiveIntegerField(editable=False)),
                (
                    "parent",
                    mptt.fields.TreeForeignKey(
                        blank=True,
                        help_text="The parent message to which this message is a reply.",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="replies",
                        to="mailing_list.mailinglistmessage",
                    ),
                ),
                (
                    "sender",
                    models.ForeignKey(
                        blank=True,
                        help_text="The registered user who sent the message.",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
