# Generated by Django 4.2.15 on 2024-10-16 18:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("mailing_list", "0002_mailinglistmessage_sender_and_more"),
    ]

    operations = [
        migrations.DeleteModel(
            name="MailingListMessage",
        ),
    ]
