# Generated by Django 4.2.15 on 2024-10-16 21:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("libraries", "0023_libraryversion_authors"),
        ("versions", "0011_version_full_release"),
        ("mailing_list", "0003_delete_mailinglistmessage"),
    ]

    operations = [
        migrations.CreateModel(
            name="EmailData",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("count", models.IntegerField()),
                (
                    "author",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="libraries.commitauthor",
                    ),
                ),
                (
                    "version",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="versions.version",
                    ),
                ),
            ],
        ),
        migrations.AddConstraint(
            model_name="emaildata",
            constraint=models.UniqueConstraint(
                fields=("author", "version"),
                name="mailing_list_emaildata_author_version_unique",
            ),
        ),
    ]
