# Generated by Django 4.2.16 on 2025-03-20 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mailing_list", "0004_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="PostingData",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("post_time", models.DateTimeField()),
                ("created", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="SubscriptionData",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("subscription_dt", models.DateTimeField()),
                ("email", models.EmailField(max_length=255)),
                ("entry_type", models.CharField(max_length=24)),
                ("list", models.CharField(max_length=24)),
                ("created", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "unique_together": {("subscription_dt", "email", "list")},
            },
        ),
    ]
