# Generated by Django 5.2.8 on 2026-01-06 01:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mailing_list", "0005_postingdata_subscriptiondata"),
    ]

    operations = [
        migrations.CreateModel(
            name="ListPosting",
            fields=[
                ("id", models.IntegerField(primary_key=True, serialize=False)),
                ("date", models.DateTimeField()),
                ("sender_id", models.CharField()),
            ],
            options={
                "db_table": "hyperkitty_email",
                "managed": False,
            },
        ),
    ]
