# Generated by Django 5.2.8 on 2026-01-05 15:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("mailing_list", "0005_postingdata_subscriptiondata"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="emaildata",
            options={"verbose_name_plural": "Email data"},
        ),
        migrations.AlterModelOptions(
            name="postingdata",
            options={"verbose_name_plural": "Posting data"},
        ),
        migrations.AlterModelOptions(
            name="subscriptiondata",
            options={"verbose_name_plural": "Subscription data"},
        ),
    ]
