# Generated by Django 6.0.7 on 2026-09-14 20:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("mailing_list", "0008_mailinglistactivity"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="mailinglistactivity",
            options={"verbose_name_plural": "Mailing List Activities"},
        ),
    ]
