# Generated by Django 6.0.2 on 2026-09-30 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mailing_list", "0009_alter_mailinglistactivity_options"),
    ]

    operations = [
        migrations.CreateModel(
            name="ListThread",
            fields=[
                ("id", models.IntegerField(primary_key=True, serialize=False)),
                ("thread_id", models.CharField()),
            ],
            options={
                "db_table": "hyperkitty_thread",
                "managed": False,
            },
        ),
    ]
