# Generated by Django 6.0.2 on 2026-10-06 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mailing_list", "0010_listthread"),
    ]

    operations = [
        migrations.CreateModel(
            name="ListMailingList",
            fields=[
                ("id", models.IntegerField(primary_key=True, serialize=False)),
                ("name", models.CharField()),
            ],
            options={
                "db_table": "hyperkitty_mailinglist",
                "managed": False,
            },
        ),
    ]
