# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-07 15:45
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="data",
            field=django.contrib.postgres.fields.jsonb.JSONField(
                blank=True, default={}, help_text="Arbitrary user data"
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="email",
            field=models.EmailField(
                db_index=True, max_length=254, unique=True, verbose_name="email address"
            ),
        ),
    ]
