# Generated by Django 3.2.2 on 2021-11-05 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_auto_20171007_1545"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="data",
            field=models.JSONField(
                blank=True, default=dict, help_text="Arbitrary user data"
            ),
        ),
    ]
