# Generated by Django 3.2.2 on 2021-11-05 09:15

from django.db import migrations


def gen_default_forum(apps, schema_editor):
    forum = apps.get_model("forum", "Forum")
    forum.objects.create(
        name="Intial Forum",
        type=0,
        slug="initial-forum",
        lft=1,
        rght=2,
        tree_id=1,
        level=0,
    )


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0003_alter_user_data"),
    ]

    operations = [
        # omit reverse_code=... if you don't want the migration to be reversible.
        migrations.RunPython(gen_default_forum, reverse_code=migrations.RunPython.noop),
    ]
