# Generated by Django 3.2.2 on 2023-03-03 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0007_user_image"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="claimed",
            field=models.BooleanField(
                default=True, verbose_name="whether this account has been claimed"
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="valid_email",
            field=models.BooleanField(
                default=True, verbose_name="whether the user's email address is valid"
            ),
        ),
    ]
