# Generated by Django 3.2.2 on 2023-03-03 21:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0008_auto_20230303_1843"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="claimed",
            field=models.BooleanField(
                default=True, verbose_name="Account has been claimed"
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="valid_email",
            field=models.BooleanField(default=True, verbose_name="Valid email address"),
        ),
    ]
