# Generated by Django 4.2 on 2023-05-08 23:11

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0009_user_display_name"),
    ]

    operations = [
        migrations.CreateModel(
            name="InvitationToken",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "token",
                    models.UUIDField(
                        default=uuid.uuid4,
                        help_text="A unique, random UUID that represents the invitation token.",
                        unique=True,
                    ),
                ),
                (
                    "expiration_date",
                    models.DateTimeField(
                        help_text="The date and time when the token expires."
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        help_text="The user who was invited to create an account.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="invitations",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
