# Generated by Django 4.2.2 on 2023-11-02 19:32

import core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0010_preferences"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="image",
            field=models.FileField(
                blank=True,
                null=True,
                upload_to="profile-images",
                validators=[
                    core.validators.FileTypeValidator(
                        extensions=[".jpg", ".jpeg", ".png"]
                    ),
                    core.validators.MaxFileSizeValidator(max_size=1048576),
                ],
            ),
        ),
    ]
