# Generated by Django 4.2.15 on 2024-10-02 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0012_user_can_update_image"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="indicate_last_login_method",
            field=models.BooleanField(
                default=False,
                help_text="Indicate on the login page the last login method used.",
            ),
        ),
    ]
