# Generated by Django 4.2.16 on 2024-11-14 02:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0014_populate_tou_notification_preference"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="delete_permanently_at",
            field=models.DateTimeField(editable=False, null=True),
        ),
    ]
