# Generated by Django 4.2.16 on 2025-02-14 22:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0016_user_hq_image"),
    ]

    operations = [
        migrations.RunSQL("UPDATE users_user SET display_name = CONCAT(first_name, ' ', last_name) WHERE display_name IS NULL;"),
    ]
