# Generated by Django 4.2.16 on 2025-02-25 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0017_populate_users_display_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="is_commit_author_name_overridden",
            field=models.BooleanField(
                default=False,
                help_text="Select to override the commit author with Username",
            ),
        ),
    ]
