# Generated by Django 5.2.7 on 2025-10-31 22:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0018_user_is_commit_author_name_overridden"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="image_uploaded",
            field=models.BooleanField(
                default=False,
                help_text="Indicates if the user manually uploaded an image, prevents import overwrites",
            ),
        ),
    ]
