# Generated by Django 5.2.8 on 2025-11-10 17:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0019_user_image_uploaded"),
    ]

    operations = [
        migrations.RenameField(
            model_name="user",
            old_name="image",
            new_name="profile_image",
        ),
    ]
