# Generated by Django 5.2.8 on 2025-11-20 22:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0020_rename_image_user_profile_image"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="badges",
        ),
        migrations.DeleteModel(
            name="Badge",
        ),
    ]
