# Generated by Django 6.0.2 on 2026-02-17 15:12

from django.db import migrations


def create_v3_testers_group(apps, schema_editor):
    Group = apps.get_model("auth", "Group")
    Group.objects.get_or_create(name="v3_testers")


def delete_v3_testers_group(apps, schema_editor):
    Group = apps.get_model("auth", "Group")
    Group.objects.filter(name="v3_testers").delete()


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0020_rename_image_user_profile_image"),
    ]

    operations = [
        migrations.RunPython(create_v3_testers_group, delete_v3_testers_group),
    ]
