# Generated by Django 6.0.2 on 2026-07-09 17:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0021_add_v3_testers_group"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="country",
        ),
        migrations.RemoveField(
            model_name="user",
            name="hide_badges",
        ),
        migrations.RemoveField(
            model_name="user",
            name="hide_mailing_list_activity",
        ),
        migrations.RemoveField(
            model_name="user",
            name="hide_github_activity",
        ),
    ]
