# Generated by Django 6.0.2 on 2026-07-01 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0021_add_v3_testers_group"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="profile_links",
            field=models.JSONField(
                blank=True,
                default=dict,
                help_text=(
                    "Public profile links keyed by type (github, website, email, "
                    "slack). Slack stores the full canonical CPPLang Slack "
                    "profile URL (https://cpplang.slack.com/team/<Member ID>) "
                    "built from the user's Slack Member ID. The Member ID is "
                    "derived for display in the edit form."
                ),
            ),
        ),
    ]
