# Generated by Django 6.0.2 on 2026-05-27 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0021_add_v3_testers_group"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="tagline",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Short one-line bio shown on profile and contributor cards.",
                max_length=160,
            ),
        ),
    ]
