# Generated by Django 6.0.2 on 2026-04-27 22:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0021_add_v3_testers_group"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="bio",
            field=models.CharField(
                blank=True,
                help_text="Short bio shown alongside the user on library cards.",
                max_length=255,
                verbose_name="bio",
            ),
        ),
    ]
