# Generated by Django 6.0.2 on 2026-07-15 00:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
        ("libraries", "0041_category_short_description"),
        ("users", "0022_user_profile_links"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="displayed_profile_role",
            field=models.CharField(
                blank=True,
                choices=[
                    ("Author", "Author"),
                    ("Maintainer", "Maintainer"),
                    ("Contributor", "Contributor"),
                    ("chief_of_staff", "Chief of Staff, C++ Alliance"),
                    ("ceo", "CEO, C++ Alliance"),
                    ("cto", "CTO, C++ Alliance"),
                    ("cfo_coo", "CFO/COO, C++ Alliance"),
                    ("cmo", "CMO, C++ Alliance"),
                    ("board_member", "Board Member, C++ Alliance"),
                    (
                        "senior_exec_assistant",
                        "Senior Executive Assistant, C++ Alliance",
                    ),
                    (
                        "creative_production_coordinator",
                        "Creative Production Coordinator, C++ Alliance",
                    ),
                    ("software_engineer", "Software Engineer, C++ Alliance"),
                    (
                        "senior_technical_writer",
                        "Senior Technical Writer, C++ Alliance",
                    ),
                    ("executive_team_alumni", "Executive Team, C++ Alliance Alumni"),
                    (
                        "technical_committee_alumni",
                        "Technical Committee, C++ Alliance Alumni",
                    ),
                    (
                        "software_engineer_alumni",
                        "Software Engineer, C++ Alliance Alumni",
                    ),
                    (
                        "fiscal_committee_member",
                        "Fiscal Committee Member, C++ Alliance",
                    ),
                ],
                default="",
                help_text="Library role the user has chosen to feature (or blank to use their default). User-controlled; C++ Alliance titles live in internal_role.",
                max_length=64,
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="displayed_profile_role_library",
            field=models.ForeignKey(
                blank=True,
                help_text='Optional library that scopes a library role, e.g. Beast -> "Boost.Beast Author". Leave blank for a generic role.',
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="libraries.library",
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="internal_role",
            field=models.CharField(
                blank=True,
                choices=[
                    ("board_member", "Board Member, C++ Alliance"),
                    ("ceo", "CEO, C++ Alliance"),
                    ("cfo_coo", "CFO/COO, C++ Alliance"),
                    ("chief_of_staff", "Chief of Staff, C++ Alliance"),
                    ("cmo", "CMO, C++ Alliance"),
                    (
                        "creative_production_coordinator",
                        "Creative Production Coordinator, C++ Alliance",
                    ),
                    ("cto", "CTO, C++ Alliance"),
                    ("executive_team_alumni", "Executive Team, C++ Alliance Alumni"),
                    (
                        "fiscal_committee_member",
                        "Fiscal Committee Member, C++ Alliance",
                    ),
                    (
                        "senior_exec_assistant",
                        "Senior Executive Assistant, C++ Alliance",
                    ),
                    (
                        "senior_technical_writer",
                        "Senior Technical Writer, C++ Alliance",
                    ),
                    ("software_engineer", "Software Engineer, C++ Alliance"),
                    (
                        "software_engineer_alumni",
                        "Software Engineer, C++ Alliance Alumni",
                    ),
                    (
                        "technical_committee_alumni",
                        "Technical Committee, C++ Alliance Alumni",
                    ),
                ],
                default="",
                help_text="C++ Alliance title, assigned by staff. This is the user's default displayed role; they may instead feature a library role they hold.",
                max_length=64,
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="resolved_profile_role",
            field=models.CharField(
                blank=True,
                default="",
                editable=False,
                help_text="Auto-derived top library role, recomputed on import. Used only when the user has set neither displayed_profile_role nor internal_role.",
                max_length=64,
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="hide_public_role",
            field=models.BooleanField(
                default=False,
                help_text="When set, the user has opted out of showing a role: it is hidden on every profile surface except their own public profile page, which still shows their best available role.",
            ),
        ),
        migrations.AddConstraint(
            model_name="user",
            constraint=models.UniqueConstraint(
                condition=models.Q(
                    (
                        "internal_role__in",
                        ("ceo", "cfo_coo", "chief_of_staff", "cmo", "cto"),
                    )
                ),
                fields=("internal_role",),
                name="unique_singular_profile_role",
                violation_error_message="This C++ Alliance title is already assigned to another user.",
            ),
        ),
    ]
