# Generated by Django 6.0.2 on 2026-07-02 17:38

import django_countries.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0022_user_profile_links"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="country",
            field=django_countries.fields.CountryField(blank=True, max_length=2),
        ),
        migrations.AddField(
            model_name="user",
            name="hide_badges",
            field=models.BooleanField(
                default=False, help_text="Hide badges from the public profile."
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="hide_github_activity",
            field=models.BooleanField(
                default=False, help_text="Hide GitHub activity from the public profile."
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="hide_mailing_list_activity",
            field=models.BooleanField(
                default=False,
                help_text="Hide mailing list activity from the public profile.",
            ),
        ),
    ]
