# Generated by Django 6.0.2 on 2026-06-23 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0022_user_profile_links"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="biography",
            field=models.TextField(
                blank=True,
                default="",
                help_text="Rich-text biography (stored as Markdown) shown on the public profile.",
                max_length=20000,
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="tagline",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Short plain-text tagline shown beside the avatar across the site.",
                max_length=70,
            ),
        ),
    ]
