# Generated by Django 6.0.2 on 2026-07-21 20:48

import core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0022_user_profile_links"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="profile_image",
            field=models.FileField(
                blank=True,
                null=True,
                upload_to="profile-images",
                validators=[
                    core.validators.FileTypeValidator(
                        extensions=[".jpg", ".jpeg", ".png"]
                    ),
                    core.validators.MaxFileSizeValidator(max_size=5242880),
                ],
            ),
        ),
    ]
