# Generated by Django 6.0.2 on 2026-07-28 13:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0022_user_country_user_hide_badges_and_more"),
        ("users", "0023_user_biography_user_tagline"),
    ]

    operations = []
