# Generated by Django 6.0.2 on 2026-07-29 17:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0023_alter_user_profile_image"),
        ("users", "0024_user_country_user_hide_badges_and_more"),
    ]

    operations = []
