# Generated by Django 6.0.2 on 2026-06-24 15:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0025_merge_20260729_1746"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="badges",
        ),
        migrations.DeleteModel(
            name="Badge",
        ),
    ]
