# Generated by Django 6.0.2 on 2026-08-04 23:22

import django.db.models.deletion
import django_extensions.db.fields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0025_user_displayed_profile_role_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="UserProfileRoutingKey",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created",
                    django_extensions.db.fields.CreationDateTimeField(
                        auto_now_add=True, verbose_name="created"
                    ),
                ),
                (
                    "modified",
                    django_extensions.db.fields.ModificationDateTimeField(
                        auto_now=True, verbose_name="modified"
                    ),
                ),
                (
                    "routing_key",
                    models.SlugField(
                        help_text='Lowercase URL segment for the user\'s public profile, e.g. "jane-doe-k3f9". Never reused.',
                        max_length=64,
                        unique=True,
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="profile_routing_keys",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "get_latest_by": "created",
                "indexes": [
                    models.Index(
                        fields=["user", "-created"],
                        name="users_userp_user_id_6f13ca_idx",
                    )
                ],
            },
        ),
    ]
