# Generated by Django 6.0.2 on 2026-08-05 17:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0025_merge_20260729_1746"),
        ("users", "0025_user_deletion_extended_scrub"),
    ]

    operations = []
