# Generated by Django 6.0.2 on 2026-08-07 00:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("badges", "0003_achievementsyncrun"),
        ("users", "0026_remove_user_badges_delete_badge"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="display_badge",
            field=models.ForeignKey(
                blank=True,
                help_text="The awarded tier the member features on their profile. Revocation is soft, so readers must check the badge is still active.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="badges.userbadge",
            ),
        ),
    ]
