[tool.interrogate]
fail-under = 100
quiet = false
verbose = 2
whitelist-regex = ["test_.*"]

[tool.ruff]
line-length = 88
target-version = "py311"

[tool.black]
line-length = 88
exclude = '''
/(
    \.git
  | migrations
)/
'''
