# Generated by Django 4.2 on 2023-05-10 18:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="News",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("slug", models.SlugField()),
                ("title", models.CharField(max_length=255)),
                ("description", models.TextField(blank=True, default="")),
                ("external_url", models.URLField(blank=True, default="")),
                ("created", models.DateTimeField(default=django.utils.timezone.now)),
                ("published", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "author",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="BlogPost",
            fields=[
                (
                    "news_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="news.news",
                    ),
                ),
                ("body", models.TextField()),
                ("abstract", models.CharField(max_length=256)),
            ],
            bases=("news.news",),
        ),
        migrations.CreateModel(
            name="Link",
            fields=[
                (
                    "news_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="news.news",
                    ),
                ),
            ],
            bases=("news.news",),
        ),
        migrations.CreateModel(
            name="Poll",
            fields=[
                (
                    "news_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="news.news",
                    ),
                ),
            ],
            bases=("news.news",),
        ),
        migrations.CreateModel(
            name="Video",
            fields=[
                (
                    "news_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="news.news",
                    ),
                ),
                ("thumbnail", models.ImageField(upload_to="")),
            ],
            bases=("news.news",),
        ),
        migrations.CreateModel(
            name="PollChoice",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("wording", models.CharField(max_length=200)),
                ("order", models.PositiveIntegerField()),
                ("votes", models.ManyToManyField(to=settings.AUTH_USER_MODEL)),
                (
                    "question",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="news.poll"
                    ),
                ),
            ],
        ),
    ]
