# Generated by Django 4.2 on 2023-05-17 01:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("news", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="entry",
            name="approved_at",
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name="entry",
            name="moderator",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="moderated_entries_set",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
