# Generated by Django 4.2.1 on 2023-05-31 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("news", "0003_rename_description_entry_content_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="entry",
            name="image",
            field=models.ImageField(blank=True, null=True, upload_to="news/%Y/%m/"),
        ),
    ]
