# Generated by Django 4.2.1 on 2023-06-14 16:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("news", "0004_alter_entry_image"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="entry",
            options={"verbose_name": "News", "verbose_name_plural": "News"},
        ),
    ]
