# Generated by Django 4.2.2 on 2023-06-22 19:05

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("news", "0005_news"),
    ]

    operations = [
        migrations.AlterField(
            model_name="entry",
            name="slug",
            field=models.SlugField(unique=True),
        ),
    ]
