# Generated by Django 4.2.2 on 2023-11-02 10:52

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("news", "0006_alter_entry_slug"),
    ]

    operations = [
        migrations.AlterField(
            model_name="entry",
            name="external_url",
            field=models.URLField(
                blank=True, default="", max_length=500, verbose_name="URL"
            ),
        ),
        migrations.AlterField(
            model_name="entry",
            name="slug",
            field=models.SlugField(max_length=300, unique=True),
        ),
    ]
