# Generated by Django 4.2.11 on 2024-03-28 23:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("news", "0008_alter_entry_image"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="news",
            options={"verbose_name": "News", "verbose_name_plural": "News Items"},
        ),
    ]
