# Generated by Django 4.2.16 on 2024-12-11 22:10

import core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("news", "0009_alter_news_options"),
    ]

    operations = [
        migrations.AddField(
            model_name="news",
            name="attachment",
            field=models.FileField(
                blank=True,
                null=True,
                upload_to="news/files/%Y/%m/",
                validators=[
                    core.validators.MaxFileSizeValidator(max_size=52428800),
                    core.validators.FileTypeValidator(
                        extensions=[".jpg", ".jpeg", ".png", ".pdf"]
                    ),
                ],
            ),
        ),
    ]
