# Generated by Django 4.2.16 on 2025-09-02 21:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("news", "0010_news_attachment"),
    ]

    operations = [
        migrations.AddField(
            model_name="entry",
            name="summary",
            field=models.TextField(
                blank=True,
                default="",
                help_text="AI generated summary. Delete to regenerate.",
            ),
        ),
    ]
