# Generated by Django 6.0.2 on 2026-07-22 20:19

import core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("news", "0014_entry_page_views"),
    ]

    operations = [
        migrations.AlterField(
            model_name="entry",
            name="image",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to="news/%Y/%m/",
                validators=[
                    core.validators.FileTypeValidator(
                        extensions=[".jpg", ".jpeg", ".png"]
                    ),
                    core.validators.MaxFileSizeValidator(max_size=5242880),
                ],
            ),
        ),
    ]
