# Generated by Django 6.0.2 on 2026-08-19 22:16

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("news", "0015_alter_entry_image"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="AIDescriptionSettings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "daily_limit",
                    models.PositiveIntegerField(
                        default=20,
                        help_text="Maximum AI description generations per user per day. Resets at midnight UTC. Applies to both the content and link generators. Superusers and members of the 'ratelimit_exempt' group are exempt.",
                        validators=[django.core.validators.MinValueValidator(1)],
                    ),
                ),
            ],
            options={
                "verbose_name": "AI Description Settings",
            },
        ),
        migrations.CreateModel(
            name="DescriptionGenerationAttempt",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "input_type",
                    models.CharField(
                        choices=[("content", "Content"), ("link", "Link")],
                        max_length=16,
                    ),
                ),
                (
                    "input_size",
                    models.PositiveIntegerField(
                        help_text="Characters of text sent to the model. For a link this is the extracted article body, not the URL."
                    ),
                ),
                (
                    "outcome",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("success", "Success"),
                            ("rate_limited", "Rate limited"),
                            ("upstream_error", "Upstream error"),
                        ],
                        max_length=16,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="description_generation_attempts",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "permissions": [
                    (
                        "bypass_description_generation_limit",
                        "Can bypass the AI description daily limit",
                    )
                ],
                "indexes": [
                    models.Index(
                        fields=["user", "created_at"],
                        name="news_descri_user_id_d2b0fb_idx",
                    )
                ],
            },
        ),
    ]
