# Generated by Django 6.0.2 on 2026-09-17 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("news", "0017_ratelimit_exempt_group"),
    ]

    operations = [
        migrations.AlterField(
            model_name="aidescriptionsettings",
            name="daily_limit",
            field=models.PositiveIntegerField(
                default=20,
                help_text="Maximum AI description generations per user per day. Resets at midnight UTC. Applies to both the content and link generators. Superusers and members of the 'ratelimit_exempt' group are exempt. Set to 0 to turn generation off for everyone, exempt users included.",
            ),
        ),
    ]
