# Generated by Django 4.2.16 on 2024-11-19 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_renderedcontent_created_renderedcontent_modified"),
    ]

    operations = [
        migrations.CreateModel(
            name="SiteSettings",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("wordcloud_ignore", models.TextField(default="")),
            ],
        ),
        migrations.AddConstraint(
            model_name="sitesettings",
            constraint=models.CheckConstraint(
                condition=models.Q(("id", 1)), name="core_sitesettings_single_instance"
            ),
        ),
        migrations.AlterModelOptions(
            name="sitesettings",
            options={"verbose_name_plural": "Site Settings"},
        ),
        migrations.AlterField(
            model_name="sitesettings",
            name="wordcloud_ignore",
            field=models.TextField(
                default="",
                help_text="A comma-separated list of words to ignore in the release report wordcloud.",
            ),
        ),
    ]
