# Generated by Django 5.2.8 on 2026-01-27 02:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0003_sitesettings_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="renderedcontent",
            name="latest_docs_path",
            field=models.CharField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="renderedcontent",
            name="latest_path_match_class",
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AddField(
            model_name="renderedcontent",
            name="latest_path_matched_indicator",
            field=models.IntegerField(
                choices=[
                    (0, "Undetermined"),
                    (1, "Direct match exists"),
                    (2, "Determined by matcher"),
                ],
                default=0,
                help_text="Indicates how the latest path should be determined.",
            ),
        ),
    ]
