# Generated by Django 5.2.8 on 2026-01-27 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0004_renderedcontent_latest_docs_path_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="sitesettings",
            name="rendered_content_replacement_start",
            field=models.DateTimeField(
                blank=True,
                editable=False,
                help_text="Set via RenderedContent admin action.",
                null=True,
            ),
        ),
    ]
