# Generated by Django 6.0.2 on 2026-05-07 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0005_sitesettings_rendered_content_replacement_start"),
        ("libraries", "0039_flag_known_bot_commit_authors"),
    ]

    operations = [
        migrations.AddField(
            model_name="sitesettings",
            name="pinned_community_libraries",
            field=models.ManyToManyField(
                blank=True,
                help_text="Pinned libraries always shown on the community page. Remaining slots are filled randomly from other libraries.",
                related_name="pinned_on_community_page",
                to="libraries.library",
            ),
        ),
    ]
