# Generated by Django 6.0.2 on 2026-05-28 22:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0006_sitesettings_pinned_community_libraries"),
        ("libraries", "0040_libraryversion_cpp_standard_maximum"),
    ]

    operations = [
        migrations.CreateModel(
            name="HomepageSettings",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "featured_library",
                    models.ForeignKey(
                        blank=True,
                        help_text="Library featured in the V3 homepage. Only flagship and core libraries present in the latest stable release are listed (beta-only libraries are excluded). If not set, a random flagship or core library will be featured.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="libraries.library",
                    ),
                ),
            ],
            options={
                "verbose_name": "Homepage Settings",
            },
        ),
    ]
