# Generated by Django 6.0.2 on 2026-06-04 00:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0007_homepagesettings"),
    ]

    operations = [
        migrations.CreateModel(
            name="PopularSearchTerm",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("label", models.CharField(max_length=128, unique=True)),
                ("rank", models.PositiveSmallIntegerField()),
                ("search_count", models.PositiveIntegerField(default=0)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["rank", "label"],
            },
        ),
        migrations.CreateModel(
            name="PopularSearchTermExclusion",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("term", models.CharField(max_length=128, unique=True)),
                ("note", models.CharField(blank=True, max_length=255)),
            ],
        ),
    ]
