# Generated by Django 6.0.2 on 2026-06-22 17:33

import django.db.models.functions.text
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0007_homepagesettings"),
    ]

    operations = [
        migrations.CreateModel(
            name="PopularSearchTerm",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("label", models.CharField(max_length=64)),
                ("rank", models.PositiveSmallIntegerField()),
                ("search_count", models.PositiveIntegerField(default=0)),
                (
                    "is_pinned",
                    models.BooleanField(
                        default=False,
                        help_text="Pin this term above Algolia-derived rows on the homepage. Use rank to order among multiple pins.",
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["-is_pinned", "rank", "label"],
                "constraints": [
                    models.UniqueConstraint(
                        django.db.models.functions.text.Lower("label"),
                        name="core_popularsearchterm_label_ci_unique",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="PopularSearchTermExclusion",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("term", models.CharField(max_length=64)),
                ("note", models.CharField(blank=True, max_length=255)),
            ],
            options={
                "constraints": [
                    models.UniqueConstraint(
                        django.db.models.functions.text.Lower("term"),
                        name="core_popularsearchtermexclusion_term_ci_unique",
                    )
                ],
            },
        ),
    ]
