# Generated by Django 6.0.2 on 2026-06-01 23:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0008_popularsearchterm_popularsearchtermexclusion"),
    ]

    operations = [
        migrations.AddField(
            model_name="popularsearchterm",
            name="is_admin_approved",
            field=models.BooleanField(default=False),
        ),
    ]
