# Generated by Django 6.0.2 on 2026-06-30 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0008_popularsearchterm_popularsearchtermexclusion"),
        ("libraries", "0041_category_short_description"),
    ]

    operations = [
        migrations.AddField(
            model_name="homepagesettings",
            name="highlighted_libraries",
            field=models.ManyToManyField(
                blank=True,
                help_text="Libraries shown in the homepage 'Explore battle tested libraries' carousel. Only flagship and core libraries present in the latest stable release are listed. If empty, a random selection of flagship or core libraries is used.",
                related_name="+",
                to="libraries.library",
            ),
        ),
    ]
