# Generated by Django 6.0.2 on 2026-06-01 23:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0009_popularsearchterm_is_admin_approved"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="popularsearchterm",
            name="is_manual_override",
        ),
    ]
