# Generated by Django 6.0.2 on 2026-06-02 18:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0010_remove_popularsearchterm_is_manual_override"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="popularsearchterm",
            name="is_admin_approved",
        ),
    ]
