# Generated by Django 6.0.7 on 2026-09-08 16:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0012_simple_unaccent_search_config"),
        ("pages", "0009_remove_legalpage_tags"),
    ]

    operations = [
        migrations.CreateModel(
            name="LegalPageSettings",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "privacy_policy_page",
                    models.ForeignKey(
                        blank=True,
                        help_text="Legal Page that presents the Privacy Policy for the site. Used in the footer on every page.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="pages.legalpage",
                    ),
                ),
                (
                    "terms_of_use_page",
                    models.ForeignKey(
                        blank=True,
                        help_text="Legal Page that presents the Terms of Use for the site. Used on sign up and in the footer on every page.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="pages.legalpage",
                    ),
                ),
            ],
            options={
                "verbose_name": "LegalPage Settings",
            },
        ),
    ]
