# Generated by Django 5.2.8 on 2026-02-16 19:49

import django.db.models.deletion
import django_extensions.db.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("libraries", "0036_releasereport_locked"),
    ]

    operations = [
        migrations.CreateModel(
            name="Email",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created",
                    django_extensions.db.fields.CreationDateTimeField(
                        auto_now_add=True, verbose_name="created"
                    ),
                ),
                (
                    "modified",
                    django_extensions.db.fields.ModificationDateTimeField(
                        auto_now=True, verbose_name="modified"
                    ),
                ),
                (
                    "email",
                    models.EmailField(db_index=True, max_length=255, unique=True),
                ),
            ],
            options={
                "ordering": ["-created"],
            },
        ),
        migrations.CreateModel(
            name="Identity",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created",
                    django_extensions.db.fields.CreationDateTimeField(
                        auto_now_add=True, verbose_name="created"
                    ),
                ),
                (
                    "modified",
                    django_extensions.db.fields.ModificationDateTimeField(
                        auto_now=True, verbose_name="modified"
                    ),
                ),
                ("name", models.CharField(blank=True, max_length=255, null=True)),
                ("description", models.TextField(blank=True, null=True)),
                (
                    "needs_review",
                    models.BooleanField(
                        default=False,
                        help_text="Flag for AI-generated identities needing manual review",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Identities",
                "ordering": ["-created"],
            },
        ),
        migrations.CreateModel(
            name="GitProfile",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created",
                    django_extensions.db.fields.CreationDateTimeField(
                        auto_now_add=True, verbose_name="created"
                    ),
                ),
                (
                    "modified",
                    django_extensions.db.fields.ModificationDateTimeField(
                        auto_now=True, verbose_name="modified"
                    ),
                ),
                ("name", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "email",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="git_profiles",
                        to="contributions.email",
                    ),
                ),
                (
                    "identity",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)s_profiles",
                        to="contributions.identity",
                    ),
                ),
            ],
            options={
                "ordering": ["-created"],
            },
        ),
        migrations.CreateModel(
            name="GithubProfile",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created",
                    django_extensions.db.fields.CreationDateTimeField(
                        auto_now_add=True, verbose_name="created"
                    ),
                ),
                (
                    "modified",
                    django_extensions.db.fields.ModificationDateTimeField(
                        auto_now=True, verbose_name="modified"
                    ),
                ),
                ("name", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "github_user_id",
                    models.BigIntegerField(
                        blank=True, db_index=True, help_text="GitHub user ID", null=True
                    ),
                ),
                (
                    "identity",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)s_profiles",
                        to="contributions.identity",
                    ),
                ),
            ],
            options={
                "ordering": ["-created"],
            },
        ),
        migrations.CreateModel(
            name="Wg21Profile",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created",
                    django_extensions.db.fields.CreationDateTimeField(
                        auto_now_add=True, verbose_name="created"
                    ),
                ),
                (
                    "modified",
                    django_extensions.db.fields.ModificationDateTimeField(
                        auto_now=True, verbose_name="modified"
                    ),
                ),
                ("name", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "identity",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)s_profiles",
                        to="contributions.identity",
                    ),
                ),
            ],
            options={
                "ordering": ["-created"],
            },
        ),
        migrations.CreateModel(
            name="Wg21Contribution",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created",
                    django_extensions.db.fields.CreationDateTimeField(
                        auto_now_add=True, verbose_name="created"
                    ),
                ),
                (
                    "modified",
                    django_extensions.db.fields.ModificationDateTimeField(
                        auto_now=True, verbose_name="modified"
                    ),
                ),
                (
                    "contributed_at",
                    models.DateTimeField(
                        blank=True,
                        db_index=True,
                        help_text="Date/time of the contribution",
                        null=True,
                    ),
                ),
                (
                    "info",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        help_text="Unique identifier (commit hash, PR number, paper ID, etc.)",
                        max_length=255,
                        null=True,
                    ),
                ),
                (
                    "comment",
                    models.TextField(
                        blank=True,
                        help_text="Commit message, comment, or title",
                        null=True,
                    ),
                ),
                (
                    "profile",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="wg21_contributions",
                        to="contributions.wg21profile",
                    ),
                ),
            ],
            options={
                "ordering": ["-contributed_at"],
            },
        ),
        migrations.CreateModel(
            name="GithubContribution",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created",
                    django_extensions.db.fields.CreationDateTimeField(
                        auto_now_add=True, verbose_name="created"
                    ),
                ),
                (
                    "modified",
                    django_extensions.db.fields.ModificationDateTimeField(
                        auto_now=True, verbose_name="modified"
                    ),
                ),
                (
                    "contributed_at",
                    models.DateTimeField(
                        blank=True,
                        db_index=True,
                        help_text="Date/time of the contribution",
                        null=True,
                    ),
                ),
                (
                    "info",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        help_text="Unique identifier (commit hash, PR number, paper ID, etc.)",
                        max_length=255,
                        null=True,
                    ),
                ),
                (
                    "comment",
                    models.TextField(
                        blank=True,
                        help_text="Commit message, comment, or title",
                        null=True,
                    ),
                ),
                (
                    "type",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("pr-create", "PR Created"),
                            ("pr-comment", "PR Commented"),
                            ("pr-review", "PR Reviewed"),
                            ("pr-approve", "PR Approved"),
                            ("pr-merge", "PR Merged"),
                            ("pr-close", "PR Closed"),
                            ("issue-create", "Issue Created"),
                            ("issue-reopened", "Issue Reopened"),
                            ("issue-comment", "Issue Commented"),
                            ("issue-close", "Issue Closed"),
                        ],
                        db_index=True,
                        help_text="Type of GitHub contribution",
                        max_length=50,
                        null=True,
                    ),
                ),
                (
                    "repo",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        help_text="Repository name",
                        max_length=255,
                        null=True,
                    ),
                ),
                (
                    "profile",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="github_contributions",
                        to="contributions.githubprofile",
                    ),
                ),
            ],
            options={
                "ordering": ["-contributed_at"],
                "unique_together": {("profile", "contributed_at", "info")},
            },
        ),
        migrations.CreateModel(
            name="GitContribution",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created",
                    django_extensions.db.fields.CreationDateTimeField(
                        auto_now_add=True, verbose_name="created"
                    ),
                ),
                (
                    "modified",
                    django_extensions.db.fields.ModificationDateTimeField(
                        auto_now=True, verbose_name="modified"
                    ),
                ),
                (
                    "contributed_at",
                    models.DateTimeField(
                        blank=True,
                        db_index=True,
                        help_text="Date/time of the contribution",
                        null=True,
                    ),
                ),
                (
                    "info",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        help_text="Unique identifier (commit hash, PR number, paper ID, etc.)",
                        max_length=255,
                        null=True,
                    ),
                ),
                (
                    "comment",
                    models.TextField(
                        blank=True,
                        help_text="Commit message, comment, or title",
                        null=True,
                    ),
                ),
                (
                    "repo",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        help_text="Repository name or path",
                        max_length=255,
                        null=True,
                    ),
                ),
                (
                    "library",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="libraries.library",
                    ),
                ),
                (
                    "profile",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="git_contributions",
                        to="contributions.gitprofile",
                    ),
                ),
            ],
            options={
                "ordering": ["-contributed_at"],
                "unique_together": {("profile", "repo", "library", "info")},
            },
        ),
    ]
