# Generated by Django 5.2.8 on 2026-02-17 01:31

import django_extensions.db.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("contributions", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="GitRepoETag",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created",
                    django_extensions.db.fields.CreationDateTimeField(
                        auto_now_add=True, verbose_name="created"
                    ),
                ),
                (
                    "modified",
                    django_extensions.db.fields.ModificationDateTimeField(
                        auto_now=True, verbose_name="modified"
                    ),
                ),
                (
                    "repo",
                    models.CharField(
                        db_index=True,
                        help_text="GitHub repository name (e.g., 'beast', 'asio')",
                        max_length=255,
                        unique=True,
                    ),
                ),
                (
                    "etag",
                    models.CharField(
                        help_text="ETag value from GitHub API response", max_length=255
                    ),
                ),
            ],
            options={
                "ordering": ["-modified"],
            },
        ),
    ]
