# Generated by Django 3.2.2 on 2022-05-28 19:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('versions', '0002_auto_20211216_1051'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Version',
        ),
        migrations.DeleteModel(
            name='VersionFile',
        ),
    ]
