# Generated by Django 3.2.2 on 2023-02-08 21:40

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("versions", "0005_version_active"),
    ]

    operations = [
        migrations.AddField(
            model_name="version",
            name="slug",
            field=models.SlugField(blank=True, null=True),
        ),
    ]
