# Generated by Django 4.2.2 on 2023-07-20 20:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("versions", "0007_version_data_version_github_url"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="versionfile",
            name="file",
        ),
        migrations.AddField(
            model_name="versionfile",
            name="display_name",
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AddField(
            model_name="versionfile",
            name="url",
            field=models.URLField(default="https://example.com"),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="versionfile",
            name="version",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="downloads",
                to="versions.version",
            ),
        ),
    ]
