# Generated by Django 4.2.2 on 2023-08-31 18:41

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("versions", "0008_remove_versionfile_file_versionfile_display_name_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="version",
            name="release_date",
            field=models.DateField(null=True),
        ),
    ]
