# Generated by Django 4.2.2 on 2023-10-11 19:10

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("versions", "0009_alter_version_release_date"),
    ]

    operations = [
        migrations.AddField(
            model_name="version",
            name="beta",
            field=models.BooleanField(
                default=False, help_text="Whether this is a beta release"
            ),
        ),
    ]
