# Generated by Django 4.2.2 on 2023-11-14 20:11

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("versions", "0010_version_beta"),
    ]

    operations = [
        migrations.AddField(
            model_name="version",
            name="full_release",
            field=models.BooleanField(
                default=True,
                help_text="Whether this is a full release and not a beta release or a development version",
            ),
        ),
    ]
