# Generated by Django 4.2.16 on 2024-11-11 20:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("versions", "0011_version_full_release"),
    ]

    operations = [
        migrations.CreateModel(
            name="Review",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("submission", models.CharField()),
                ("submitter", models.CharField()),
                ("review_manager", models.CharField(blank=True, default="Needed!")),
                ("review_dates", models.CharField()),
                ("github_link", models.URLField(blank=True, default="")),
                ("documentation_link", models.URLField(blank=True, default="")),
            ],
        ),
        migrations.CreateModel(
            name="ReviewResult",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("short_description", models.CharField()),
                ("is_most_recent", models.BooleanField(default=True)),
                ("announcement_link", models.URLField(blank=True, default="")),
                (
                    "review",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="results",
                        to="versions.review",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "review results",
            },
        ),
    ]
