# Generated by Django 4.2.16 on 2024-12-02 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("versions", "0013_version_release_report_cover_image"),
    ]

    operations = [
        migrations.AddField(
            model_name="version",
            name="sponsor_message",
            field=models.TextField(
                blank=True,
                default="",
                help_text='Message to show in release reports on the "Fiscal Sponsorship Committee" page.',
            ),
        ),
    ]
