# Generated by Django 4.2.16 on 2024-12-18 18:25

from django.db import migrations
from django.db.models import Q


def delete_stub_users(apps, schema_editor):
    User = apps.get_model("users", "User")
    print("\nDeleting stub users")
    User.objects.filter(email__endswith="@example.com", claimed=False).filter(
        Q(submitted_reviews__isnull=False) | Q(managed_reviews__isnull=False)
    ).delete()


class Migration(migrations.Migration):

    dependencies = [
        ("versions", "0014_version_sponsor_message"),
    ]

    operations = [
        migrations.RunPython(
            delete_stub_users,
            migrations.RunPython.noop,  # Not feasible to re-populate these users
        ),
    ]
