# Generated by Django 4.2.16 on 2025-07-03 21:09

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("versions", "0018_version_financial_committee_members"),
    ]

    operations = [
        migrations.CreateModel(
            name="ReportConfiguration",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "version",
                    models.CharField(
                        help_text="The version name this report configuration is for.",
                        max_length=256,
                    ),
                ),
                (
                    "release_report_cover_image",
                    models.ImageField(
                        blank=True, null=True, upload_to="release_report_cover/"
                    ),
                ),
                (
                    "sponsor_message",
                    models.TextField(
                        blank=True,
                        default="",
                        help_text='Message to show in release reports on the "Fiscal Sponsorship Committee" page.',
                    ),
                ),
                (
                    "financial_committee_members",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Financial Committee members who are responsible for this release.",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
