# Generated by Django 4.2.16 on 2025-07-12 00:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("versions", "0020_decouple_report_configuration_migration"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="version",
            name="financial_committee_members",
        ),
        migrations.RemoveField(
            model_name="version",
            name="release_report_cover_image",
        ),
        migrations.RemoveField(
            model_name="version",
            name="sponsor_message",
        ),
        migrations.AlterField(
            model_name="reportconfiguration",
            name="version",
            field=models.CharField(
                help_text="The version name for this report configuration. e.g. boost-1.75.0",
                max_length=256,
                unique=True,
            ),
        ),
    ]
