# Generated by Django 4.2.16 on 2025-07-15 20:53

from django.db import migrations, models
import versions.utils.model_validators


class Migration(migrations.Migration):

    dependencies = [
        ("versions", "0021_remove_version_financial_committee_members_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="reportconfiguration",
            name="version",
            field=models.CharField(
                help_text="The version name for this report configuration. e.g. boost-1.75.0",
                max_length=256,
                unique=True,
                validators=[
                    versions.utils.model_validators.validate_version_name_format
                ],
            ),
        ),
    ]
