# Generated by Django 4.2.16 on 2025-08-12 21:59

from django.db import migrations, models


def update_fully_imported(apps, schema_editor):
    Version = apps.get_model("versions", "Version")
    Version.objects.all().update(fully_imported=True)

class Migration(migrations.Migration):

    dependencies = [
        ("versions", "0022_alter_reportconfiguration_version"),
    ]

    operations = [
        migrations.AddField(
            model_name="version",
            name="fully_imported",
            field=models.BooleanField(
                default=False,
                help_text="Whether this version has been fully imported and is ready for use.",
            ),
        ),
        migrations.RunPython(update_fully_imported, migrations.RunPython.noop),
    ]
