# Generated by Django 4.2.16 on 2025-08-12 21:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("versions", "0022_alter_reportconfiguration_version"),
    ]

    operations = [
        migrations.AddField(
            model_name="version",
            name="fully_imported",
            field=models.BooleanField(
                default=False,
                help_text="Whether this version has been fully imported and is ready for use.",
            ),
        ),
    ]
