# Generated by Django 4.2.16 on 2025-08-22 22:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("versions", "0023_version_fully_imported"),
    ]

    operations = [
        migrations.AlterField(
            model_name="versionfile",
            name="checksum",
            field=models.CharField(default=None, max_length=64),
        ),
        migrations.AlterUniqueTogether(
            name="versionfile",
            unique_together={("version", "checksum")},
        ),
    ]
