# Generated by Django 5.2.7 on 2025-10-27 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("versions", "0024_alter_versionfile_checksum_and_more"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="version",
            index=models.Index(
                fields=["active", "fully_imported"],
                name="versions_ve_active_ae486b_idx",
            ),
        ),
    ]
