# Generated by Django 5.2.8 on 2025-12-16 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("versions", "0025_version_versions_ve_active_ae486b_idx"),
    ]

    operations = [
        migrations.AlterField(
            model_name="versionfile",
            name="operating_system",
            field=models.CharField(
                choices=[
                    ("Unix", "Unix"),
                    ("Windows", "Windows"),
                    ("Windows (Bin)", "Windows (Bin)"),
                ],
                default="Unix",
                max_length=15,
            ),
        ),
    ]
