# Generated by Django 6.0.2 on 2026-05-11 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("versions", "0026_alter_versionfile_operating_system"),
    ]

    operations = [
        migrations.AddField(
            model_name="version",
            name="whats_new",
            field=models.TextField(
                blank=True,
                default="",
                help_text="AI-generated What's New summary (markdown bullets). Clear to regenerate on next release-notes import.",
            ),
        ),
        migrations.AddField(
            model_name="version",
            name="whats_new_approved",
            field=models.BooleanField(
                default=False,
                help_text="Public site only renders the summary when this is True.",
            ),
        ),
        migrations.AddField(
            model_name="version",
            name="whats_new_generated_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
