# Generated by Django 4.2 on 2023-05-12 22:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("versions", "0007_version_data_version_github_url"),
        ("libraries", "0007_auto_20230323_1912"),
    ]

    operations = [
        migrations.AlterField(
            model_name="libraryversion",
            name="library",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="library_version",
                to="libraries.library",
            ),
        ),
        migrations.AlterField(
            model_name="libraryversion",
            name="version",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="library_version",
                to="versions.version",
            ),
        ),
    ]
