# Generated by Django 4.2.1 on 2023-05-18 21:46

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("libraries", "0008_alter_libraryversion_library_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="library",
            name="first_github_tag_date",
            field=models.DateField(
                blank=True,
                help_text=(
                    "The date of the first release, based on the date of the "
                    "commit of the first GitHub tag."
                ),
                null=True,
            ),
        ),
    ]
