# Generated by Django 4.2.1 on 2023-05-25 20:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("libraries", "0010_commitdata"),
    ]

    operations = [
        migrations.AlterField(
            model_name="commitdata",
            name="library",
            field=models.ForeignKey(
                help_text="The Library to which these commits belong.",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="commit_data",
                to="libraries.library",
            ),
        ),
    ]
