# Generated by Django 4.2.2 on 2023-08-03 15:48

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("libraries", "0011_alter_libraryversion_library_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="libraryversion",
            name="documentation_url",
            field=models.CharField(
                blank=True,
                help_text="The path to the docs for this library version.",
                max_length=255,
                null=True,
            ),
        ),
    ]
