# Generated by Django 4.2.2 on 2023-08-17 22:24

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("libraries", "0012_libraryversion_documentation_url"),
    ]

    operations = [
        migrations.AddField(
            model_name="library",
            name="featured",
            field=models.BooleanField(
                db_index=True,
                default=False,
                help_text="Should this library be featured on the home page?",
            ),
        ),
    ]
