# Generated by Django 4.2.2 on 2023-09-07 21:33

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("libraries", "0014_remove_library_closed_prs_per_month_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="library",
            name="data",
            field=models.JSONField(default=dict),
        ),
    ]
