# Generated by Django 4.2.2 on 2023-09-08 16:35

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("libraries", "0015_library_data"),
    ]

    operations = [
        migrations.AddField(
            model_name="libraryversion",
            name="data",
            field=models.JSONField(
                default=dict,
                help_text="Contains the libraries.json for this library-version",
            ),
        ),
        migrations.AlterField(
            model_name="library",
            name="data",
            field=models.JSONField(
                default=dict, help_text="Contains the libraries.json for this library"
            ),
        ),
    ]
