# Generated by Django 4.2.2 on 2023-09-19 20:29

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("libraries", "0016_libraryversion_data_alter_library_data"),
        ("libraries", "0016_remove_library_first_github_tag_date"),
    ]

    operations = []
