# Generated by Django 4.2.2 on 2024-02-12 19:23

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("libraries", "0017_merge_20230919_2029"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="commitdata",
            options={"verbose_name_plural": "Commit Data"},
        ),
    ]
