# Generated by Django 4.2.2 on 2024-02-18 00:58

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("libraries", "0018_alter_commitdata_options"),
        ("libraries", "0018_libraryversion_missing_docs"),
    ]

    operations = []
