# Generated by Django 4.2.15 on 2024-09-23 18:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("libraries", "0021_commitauthor_commitauthoremail_commit_and_more"),
    ]

    operations = [
        migrations.DeleteModel(
            name="CommitData",
        ),
    ]
