# Generated by Django 4.2.15 on 2024-10-16 17:52

from django.db import migrations, models
import django.db.models.functions.text


class Migration(migrations.Migration):

    dependencies = [
        ("libraries", "0022_delete_commitdata"),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="library",
            constraint=models.UniqueConstraint(
                django.db.models.functions.text.Upper("slug"),
                name="slug_unique_case_insensitive",
            ),
        ),
    ]
