# Generated by Django 4.2.15 on 2024-10-08 23:05

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("libraries", "0022_delete_commitdata"),
    ]

    operations = [
        migrations.AddField(
            model_name="libraryversion",
            name="authors",
            field=models.ManyToManyField(
                related_name="author_libraryversions", to=settings.AUTH_USER_MODEL
            ),
        ),
    ]
