# Generated by Django 4.2.16 on 2024-10-28 22:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("libraries", "0023_library_slug_unique_case_insensitive"),
        ("libraries", "0023_libraryversion_authors"),
    ]

    operations = []
