# Generated by Django 4.2.16 on 2024-10-30 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("libraries", "0024_merge_20241028_2234"),
    ]

    operations = [
        migrations.AddField(
            model_name="libraryversion",
            name="deletions",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="libraryversion",
            name="files_changed",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="libraryversion",
            name="insertions",
            field=models.IntegerField(default=0),
        ),
    ]
