# Generated by Django 4.2.16 on 2024-12-05 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("libraries", "0026_libraryversion_cpp_standard_minimum_and_description"),
    ]

    operations = [
        migrations.AddField(
            model_name="libraryversion",
            name="dependencies",
            field=models.ManyToManyField(
                blank=True, related_name="dependents", to="libraries.library"
            ),
        ),
    ]
