# Generated by Django 4.2.16 on 2025-02-05 21:58

import core.custom_model_fields
import core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("libraries", "0027_libraryversion_dependencies"),
    ]

    operations = [
        migrations.AddField(
            model_name="library",
            name="graphic",
            field=core.custom_model_fields.NullableFileField(
                blank=True,
                default=None,
                null=True,
                upload_to="library_graphics",
                validators=[
                    core.validators.FileTypeValidator(
                        extensions=[".jpg", ".jpeg", ".png"]
                    ),
                    core.validators.MaxFileSizeValidator(max_size=1048576),
                ],
                verbose_name="Library Graphic",
            ),
        ),
        migrations.AddField(
            model_name="library",
            name="is_good",
            field=models.BooleanField(
                default=False,
                help_text="Is this library considered 'good' by the Boost community?",
                verbose_name="Good Library",
            ),
        ),
    ]
