# Generated by Django 4.2.16 on 2025-02-11 16:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("libraries", "0028_library_graphic_library_is_good"),
        ("libraries", "0028_wordcloudmergeword"),
    ]

    operations = []
