# Generated by Django 4.2.16 on 2025-08-08 21:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("libraries", "0030_commitauthor_user"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="library",
            name="active_development",
        ),
    ]
