# Generated by Django 4.2.16 on 2025-07-25 21:56

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("libraries", "0030_commitauthor_user"),
    ]

    operations = [
        migrations.AddField(
            model_name="commitauthoremail",
            name="claim_hash",
            field=models.UUIDField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="commitauthoremail",
            name="claim_hash_expiration",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name="commitauthoremail",
            name="claim_verified",
            field=models.BooleanField(default=False),
        ),
    ]
