# Generated by Django 4.2.16 on 2025-09-05 18:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("libraries", "0031_commitauthoremail_claim_hash_and_more"),
        ("libraries", "0031_remove_library_active_development"),
    ]

    operations = []
