# Generated by Django 4.2.24 on 2025-09-18 23:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("libraries", "0032_merge_20250905_1825"),
    ]

    operations = [
        migrations.AddField(
            model_name="libraryversion",
            name="cpp20_module_support",
            field=models.BooleanField(default=False),
        ),
    ]
