# Generated by Django 4.2.24 on 2025-10-16 23:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("libraries", "0033_libraryversion_cpp20_module_support"),
    ]

    operations = [
        migrations.RunSQL(
            sql="UPDATE libraries_libraryversion SET documentation_url = REPLACE(documentation_url, '/boost_', '/') WHERE documentation_url LIKE '%/boost_%';",
            reverse_sql="UPDATE libraries_libraryversion SET documentation_url = REPLACE(documentation_url, '/doc/libs/', '/doc/libs/boost_') WHERE documentation_url LIKE '/doc/libs/[0-9]%';",
        ),
    ]
