# Generated by Django 5.2.7 on 2025-11-11 22:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("libraries", "0035_releasereport"),
    ]

    operations = [
        migrations.AddField(
            model_name="releasereport",
            name="locked",
            field=models.BooleanField(
                default=False,
                help_text="Can't be overwritten during release report publish. Blocks task-based publishing.",
            ),
        ),
    ]
