# Generated by Django 5.2.8 on 2026-02-03 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("libraries", "0036_releasereport_locked"),
    ]

    operations = [
        migrations.AddField(
            model_name="library",
            name="tier",
            field=models.IntegerField(
                blank=True,
                choices=[
                    (10, "Flagship"),
                    (20, "Core"),
                    (30, "Deprecated"),
                    (40, "Legacy"),
                ],
                help_text="The tier classification for this library",
                null=True,
            ),
        ),
    ]
