# Generated by Django 6.0.2 on 2026-04-20 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("libraries", "0037_library_tier"),
    ]

    operations = [
        migrations.AddField(
            model_name="commitauthor",
            name="is_bot",
            field=models.BooleanField(
                default=False,
                help_text="Exclude from contributor lists. Auto-set on import for known bot names; editable here for anything detected later.",
            ),
        ),
    ]
