# Generated by Django 6.0.2 on 2026-05-11 23:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("libraries", "0039_flag_known_bot_commit_authors"),
    ]

    operations = [
        migrations.AddField(
            model_name="libraryversion",
            name="cpp_standard_maximum",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
