# Generated by Django 6.0.2 on 2026-05-28 00:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("libraries", "0040_libraryversion_cpp_standard_maximum"),
    ]

    operations = [
        migrations.CreateModel(
            name="LibraryCodeSnippet",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("code", models.TextField()),
                (
                    "library",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="code_snippet",
                        to="libraries.library",
                    ),
                ),
            ],
        ),
    ]
