# Generated by Django 6.0.2 on 2026-05-14 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("libraries", "0040_libraryversion_cpp_standard_maximum"),
    ]

    operations = [
        migrations.AddField(
            model_name="category",
            name="short_description",
            field=models.TextField(
                blank=True,
                default="",
                help_text="Short marketing copy shown on the Learn page category carousel.",
            ),
        ),
    ]
