# Generated by Django 6.0.2 on 2026-07-06 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("libraries", "0041_category_short_description"),
    ]

    operations = [
        migrations.AddField(
            model_name="library",
            name="slack_url",
            field=models.URLField(
                blank=True,
                default="",
                help_text="URL of the dedicated Slack channel for this library. Falls back to the general Boost Slack when blank.",
                max_length=500,
            ),
        ),
    ]
