# Generated by Django 6.0.2 on 2026-07-15 13:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("libraries", "0041_category_short_description"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="commitauthoremail",
            name="claimed_by",
            field=models.ForeignKey(
                blank=True,
                help_text="Who asked to claim this email. Public attribution (author.user) is only bound at verification.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="commit_email_claims",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
