# Generated by Django 6.0.2 on 2026-07-06 22:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("libraries", "0042_library_slack_url"),
    ]

    operations = [
        migrations.AddField(
            model_name="libraryversion",
            name="website_adoc",
            field=models.JSONField(
                blank=True,
                help_text="Parsed content of the library's optional meta/website.adoc (About, Playground, Designed for, Links, Install, Benchmarks, Freeform). Null when the repo has no website.adoc for this version.",
                null=True,
            ),
        ),
    ]
