# Generated by Django 6.0.2 on 2026-08-19 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("libraries", "0043_libraryversion_website_adoc_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="commit",
            name="docs_files_changed",
            field=models.PositiveIntegerField(default=0),
        ),
    ]
