# Generated by Django 6.0.2 on 2026-08-14 19:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("libraries", "0043_backfill_commitauthoremail_claimed_by"),
        ("libraries", "0043_libraryversion_website_adoc_and_more"),
    ]

    operations = []
