# Generated by Django 6.0.7 on 2026-08-28 18:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("libraries", "0045_seed_category_descriptions"),
        ("libraries", "0045_unbind_unverified_commit_author_claims"),
    ]

    operations = []
