# Generated by Django 6.0.2 on 2026-08-28 18:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("libraries", "0046_commit_docs_files_changed"),
        ("libraries", "0046_merge_20260828_1850"),
    ]

    operations = []
