# Generated by Django 6.0.2 on 2026-10-01 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("libraries", "0047_merge_20260828_1858"),
    ]

    operations = [
        migrations.AddField(
            model_name="library",
            name="cpp_standard_maximum",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
