# Generated by Django 6.0.2 on 2026-08-12 00:49

import core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Feedback",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "feedback_type",
                    models.CharField(
                        choices=[
                            ("bug", "Bug"),
                            ("suggestion", "Suggestion"),
                            ("question", "Question"),
                            ("confusing", "Confusing"),
                            ("design", "Design"),
                            ("usability", "Usability"),
                            ("incorrect_information", "Incorrect information"),
                            ("other", "Other"),
                        ],
                        default="other",
                        max_length=30,
                    ),
                ),
                ("message", models.TextField(max_length=4000)),
                (
                    "image",
                    models.ImageField(
                        blank=True,
                        help_text="Optional screenshot showing the problem.",
                        null=True,
                        upload_to="feedback/%Y/%m/",
                        validators=[
                            core.validators.FileTypeValidator(
                                extensions=[".jpg", ".jpeg", ".png"]
                            ),
                            core.validators.MaxFileSizeValidator(max_size=2097152),
                        ],
                    ),
                ),
                ("page_url", models.CharField(blank=True, default="", max_length=1000)),
                ("url_name", models.CharField(blank=True, default="", max_length=100)),
                (
                    "boost_version",
                    models.CharField(blank=True, default="", max_length=100),
                ),
                (
                    "user_agent",
                    models.CharField(blank=True, default="", max_length=400),
                ),
                ("diagnostics", models.JSONField(blank=True, default=dict)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("new", "New"),
                            ("triaged", "Triaged"),
                            ("actioned", "Actioned"),
                            ("wont_fix", "Won't fix"),
                        ],
                        default="new",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        default=None,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="feedback",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "feedback",
                "ordering": ["-created_at"],
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(("message", ""), _negated=True),
                        name="feedback_requires_message",
                    )
                ],
            },
        ),
    ]
