# Generated by Django 6.0.2 on 2026-09-09 21:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("feedback", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="feedback",
            name="contact_email",
            field=models.EmailField(blank=True, default="", max_length=254),
        ),
    ]
