Image: registry.revsys.com/boost
ImageTag: 0.0.51

djangoDebug: true

nginxImageTag: "1.21-alpine"

deploymentEnvironment: &env dev
clientMaxBodySize: 250m

replicaCount: "2"

## NOTE ##
# set publcFqdn to the target domain. `www` will be prepended to the domain
# where necessary

initCommands:
  # migrate moved to a Job
  # - name: migrate
  #   command: ./manage.py migrate --noinput
  - name: collectstatic
    command: ./manage.py collectstatic --noinput

publicFqdn: &fqdn boost.revsys.dev
publicFqdn2: &fqdn2 boost.org
publicFqdn3: &fqdn3 preview.boost.org

Env:
  - name: DJANGO_SETTINGS_MODULE
    value: "config.settings"
  - name: PGHOST
    valueFrom:
      secretKeyRef:
        name: pg
        key: dbhost
  - name: PGPORT
    valueFrom:
      secretKeyRef:
        name: pg
        key: dbport
  - name: PGDATABASE
    valueFrom:
      secretKeyRef:
        name: pg
        key: dbname
  - name: PGUSER
    valueFrom:
      secretKeyRef:
        name: pg
        key: dbuser
  - name: PGPASSWORD
    valueFrom:
      secretKeyRef:
        name: pg
        key: dbpass
  - name: DJANGO_FQDN
    value: *fqdn
  - name: ALLOWED_HOSTS
    value: "boost.revsys.dev, www.boost.revsys.dev, boost.org, www.boost.org, preview.boost.org, www.preview.boost.org"
  - name: CSRF_TRUSTED_ORIGINS
    value: "http://0.0.0.0, http://localhost, https://boost.revsys.dev, https://www.boost.revsys.dev, https://boost.org, https://www.boost.org, https://preview.boost.org, https://www.preview.boost.org"

  # silence django deprecation warnings
  - name: PYTHONWARNINGS
    value: ignore
  - name: X_NODE_NAME
    valueFrom:
      fieldRef:
        fieldPath: spec.nodeName
        apiVersion: v1
  - name: X_POD_IP
    valueFrom:
      fieldRef:
        fieldPath: status.podIP
        apiVersion: v1
  - name: X_KUBE_NAMESPACE
    valueFrom:
      fieldRef:
        fieldPath: metadata.namespace
        apiVersion: v1
  - name: X_DEPLOYMENT_ENV
    value: *env
  - name: X_POD_NAME
    valueFrom:
      fieldRef:
        fieldPath: metadata.name
        apiVersion: v1
  - name: DJANGO_DEBUG
    value: "false"
  - name: SECRET_KEY
    valueFrom:
      secretKeyRef:
        name: django-secret-key
        key: key
  - name: ENVIRONMENT_NAME
    value: "Development Environment"
  # Uploaded Media Bucket
  - name: AWS_ACCESS_KEY_ID
    valueFrom:
      secretKeyRef:
        name: media-bucket
        key: access_key
  - name: AWS_SECRET_ACCESS_KEY
    valueFrom:
      secretKeyRef:
        name: media-bucket
        key: secret_key
  - name: MEDIA_BUCKET_NAME
    value: boost-dev-media
  # Staticly generated content bucket (Antora docs, etc)
  - name: STATIC_CONTENT_AWS_ACCESS_KEY_ID
    valueFrom:
      secretKeyRef:
        name: static-content
        key: access_key
  - name: STATIC_CONTENT_AWS_SECRET_ACCESS_KEY
    valueFrom:
      secretKeyRef:
        name: static-content
        key: secret_key
  - name: STATIC_CONTENT_BUCKET_NAME
    valueFrom:
      secretKeyRef:
        name: static-content
        key: bucket_name
  - name: MAILGUN_API_KEY
    valueFrom:
      secretKeyRef:
        name: mailgun
        key: key
  - name: MAILMAN_REST_API_URL
    valueFrom:
      secretKeyRef:
        name: mailman
        key: api_url
  - name: MAILMAN_REST_API_USER
    valueFrom:
      secretKeyRef:
        name: mailman
        key: api_user
  - name: MAILMAN_REST_API_PASS
    valueFrom:
      secretKeyRef:
        name: mailman
        key: api_pass
  - name: MAILMAN_ARCHIVER_KEY
    valueFrom:
      secretKeyRef:
        name: mailman
        key: archiver_key
  - name: MAILMAN_ELASTIC_INDEX
    valueFrom:
      secretKeyRef:
        name: mailman
        key: elastic_index
  - name: MAILMAN_HAYSTACK_URL
    valueFrom:
      secretKeyRef:
        name: mailman
        key: haystack_url
  - name: GITHUB_TOKEN
    valueFrom:
      secretKeyRef:
        name: githubtoken
        key: key
  # Static content cache timeout
  - name: STATIC_CACHE_TIMEOUT
    value: "60"

# Volumes
Volumes:
  - name: run
    emptyDir: {}
  - name: staticfiles
    emptyDir: {}
  - name: ngx
    configMap:
      name: nginx-config--boost

VolumeMounts:
  - name: staticfiles
    mountPath: /code/static_deploy
  - name: run
    mountPath: /run

NginxVolumeMounts:
  - name: staticfiles
    mountPath: /code/static_deploy
  - name: run
    mountPath: /run

hostAliases: {}

ingressType: nginx
redisInstall: false
celeryInstall: false
