Image: us-central1-docker.pkg.dev/boostorg-project1/website/website
ImageTag: ac20d69

djangoDebug: true

nginxImageTag: "1.21-alpine"

deploymentEnvironment: &env dev
clientMaxBodySize: 250m

replicaCount: "2"

## NOTE ##
# set publcFqdn to the target domain. `www` will be prepended to the domain
# where necessary

initCommands:
  # migrate moved to a Job
  # - name: migrate
  #   command: ./manage.py migrate --noinput
  - name: collectstatic
    command: ./manage.py collectstatic --noinput

publicFqdn: &fqdn cppal-dev.boost.cppalliance.org
publicFqdn2: &fqdn2 boost.org
publicFqdn3: &fqdn3 cppal-dev2.boost.cppalliance.org

Env:
  - name: DJANGO_SETTINGS_MODULE
    value: "config.settings"
  - name: PGHOST
    valueFrom:
      secretKeyRef:
        name: pg
        key: dbhost
  - name: PGPORT
    valueFrom:
      secretKeyRef:
        name: pg
        key: dbport
  - name: PGDATABASE
    valueFrom:
      secretKeyRef:
        name: pg
        key: dbname
  - name: PGUSER
    valueFrom:
      secretKeyRef:
        name: pg
        key: dbuser
  - name: PGPASSWORD
    valueFrom:
      secretKeyRef:
        name: pg
        key: dbpass
  - name: DJANGO_FQDN
    value: *fqdn
  - name: ALLOWED_HOSTS
    value: "cppal-dev.boost.cppalliance.org, www.cppal-dev.boost.cppalliance.org, boost.org, www.boost.org, cppal-dev2.boost.cppalliance.org, www.cppal-dev2.boost.cppalliance.org"
  - name: CSRF_TRUSTED_ORIGINS
    value: "http://0.0.0.0, http://localhost, https://cppal-dev.boost.cppalliance.org, https://www.cppal-dev.boost.cppalliance.org, https://boost.org, https://www.boost.org, https://cppal-dev2.boost.cppalliance.org, https://www.cppal-dev2.boost.cppalliance.org"

  # silence django deprecation warnings
  - name: PYTHONWARNINGS
    value: ignore
  - name: X_NODE_NAME
    valueFrom:
      fieldRef:
        fieldPath: spec.nodeName
        apiVersion: v1
  - name: X_POD_IP
    valueFrom:
      fieldRef:
        fieldPath: status.podIP
        apiVersion: v1
  - name: X_KUBE_NAMESPACE
    valueFrom:
      fieldRef:
        fieldPath: metadata.namespace
        apiVersion: v1
  - name: X_DEPLOYMENT_ENV
    value: *env
  - name: X_POD_NAME
    valueFrom:
      fieldRef:
        fieldPath: metadata.name
        apiVersion: v1
  - name: DJANGO_DEBUG
    value: "false"
  - name: SECRET_KEY
    valueFrom:
      secretKeyRef:
        name: django-secret-key
        key: key
  - name: ENVIRONMENT_NAME
    value: "Development Environment"
  - name: AWS_ACCESS_KEY_ID
    valueFrom:
      secretKeyRef:
        name: media-bucket
        key: access_key
  - name: AWS_SECRET_ACCESS_KEY
    valueFrom:
      secretKeyRef:
        name: media-bucket
        key: secret_key
  - name: MEDIA_BUCKET_NAME
    value: boost.org-cppal-dev-v2.media
  - name: AWS_S3_ENDPOINT_URL
    value: https://s3.us-east-2.amazonaws.com
  - name: AWS_S3_REGION_NAME
    value: us-east-2
 # Staticly generated content bucket (Antora docs, etc)
  - name: STATIC_CONTENT_AWS_ACCESS_KEY_ID
    valueFrom:
      secretKeyRef:
        name: static-content
        key: access_key
  - name: STATIC_CONTENT_AWS_SECRET_ACCESS_KEY
    valueFrom:
      secretKeyRef:
        name: static-content
        key: secret_key
  - name: STATIC_CONTENT_BUCKET_NAME
    valueFrom:
      secretKeyRef:
        name: static-content
        key: bucket_name
  - name: MAILGUN_API_KEY
    valueFrom:
      secretKeyRef:
        name: mailgun
        key: key
  - name: MAILGUN_SENDER_DOMAIN
    value: cppal-dev.boost.cppalliance.org
  - name: GITHUB_TOKEN
    valueFrom:
      secretKeyRef:
        name: githubtoken
        key: key
  # Static content cache timeout
  - name: STATIC_CACHE_TIMEOUT
    value: "60"
  - name: CELERY_BROKER
    value: redis://redis:6379/0
  - name: CELERY_BACKEND
    value: redis://redis:6379/0

# Volumes
Volumes:
  - name: run
    emptyDir: {}
  - name: staticfiles
    emptyDir: {}
  - name: ngx
    configMap:
      name: nginx-config--boost
  - name: htpw
    configMap:
      name: htpasswd

VolumeMounts:
  - name: staticfiles
    mountPath: /code/static_deploy
  - name: run
    mountPath: /run

NginxVolumeMounts:
  - name: staticfiles
    mountPath: /code/static_deploy
  - name: run
    mountPath: /run

hostAliases:
  - ip: "10.67.224.3"
    hostnames:
      - "redis"

ingressType: gce
managedCertName: managed-cert-cppal-dev,managed-cert-cppal-dev2
secretCertName: boostorgcert
ingressStaticIp: cppal-dev-ingress1
redisInstall: false
celeryInstall: true
