# Generated by Django 6.0.2 on 2026-02-20 14:56

import modelcluster.contrib.taggit
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("pages", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="routablehomepage",
            name="tags",
            field=modelcluster.contrib.taggit.ClusterTaggableManager(
                blank=True,
                help_text="A comma-separated list of tags.",
                through="pages.TaggedContent",
                to="pages.ContentTag",
                verbose_name="Tags",
            ),
        ),
    ]
