# Generated by Django 6.0.2 on 2026-02-20 19:08

import django.db.models.deletion
import modelcluster.contrib.taggit
import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pages", "0002_routablehomepage_tags"),
        ("wagtailcore", "0096_referenceindex_referenceindex_source_object_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="PostIndexPage",
            fields=[
                (
                    "page_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="wagtailcore.page",
                    ),
                ),
                (
                    "tags",
                    modelcluster.contrib.taggit.ClusterTaggableManager(
                        blank=True,
                        help_text="A comma-separated list of tags.",
                        through="pages.TaggedContent",
                        to="pages.ContentTag",
                        verbose_name="Tags",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
            bases=("wagtailcore.page",),
        ),
        migrations.CreateModel(
            name="PostPage",
            fields=[
                (
                    "page_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="wagtailcore.page",
                    ),
                ),
                (
                    "content",
                    wagtail.fields.StreamField(
                        [
                            ("rich_text", 0),
                            ("markdown", 1),
                            ("url", 2),
                            ("video", 5),
                            ("poll", 7),
                        ],
                        block_lookup={
                            0: ("wagtail.blocks.RichTextBlock", (), {}),
                            1: ("wagtailmarkdown.blocks.MarkdownBlock", (), {}),
                            2: ("wagtail.blocks.URLBlock", (), {}),
                            3: ("wagtail.embeds.blocks.EmbedBlock", (), {}),
                            4: ("wagtail.images.blocks.ImageChooserBlock", (), {}),
                            5: (
                                "wagtail.blocks.StructBlock",
                                [[("video", 3), ("thumbnail", 4)]],
                                {"label": "Video"},
                            ),
                            6: ("wagtail.blocks.CharBlock", (), {"max_length": 200}),
                            7: (
                                "wagtail.blocks.StreamBlock",
                                [[("poll_choice", 6)]],
                                {},
                            ),
                        },
                    ),
                ),
                (
                    "tags",
                    modelcluster.contrib.taggit.ClusterTaggableManager(
                        blank=True,
                        help_text="A comma-separated list of tags.",
                        through="pages.TaggedContent",
                        to="pages.ContentTag",
                        verbose_name="Tags",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
            bases=("wagtailcore.page",),
        ),
    ]
