# Generated by Django 6.0.2 on 2026-06-03 17:59

import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("pages", "0002_postpage_video_thumbnail"),
    ]

    operations = [
        migrations.AlterField(
            model_name="postpage",
            name="content",
            field=wagtail.fields.StreamField(
                [
                    ("rich_text", 0),
                    ("blog", 1),
                    ("news", 1),
                    ("url", 2),
                    ("video", 5),
                    ("poll", 7),
                ],
                block_lookup={
                    0: ("wagtail.blocks.RichTextBlock", (), {}),
                    1: ("wagtailmarkdown.blocks.MarkdownBlock", (), {}),
                    2: ("wagtail.blocks.URLBlock", (), {}),
                    3: ("wagtail.embeds.blocks.EmbedBlock", (), {}),
                    4: ("wagtail.images.blocks.ImageChooserBlock", (), {}),
                    5: (
                        "wagtail.blocks.StructBlock",
                        [[("video", 3), ("thumbnail", 4)]],
                        {"label": "Video"},
                    ),
                    6: ("wagtail.blocks.CharBlock", (), {"max_length": 200}),
                    7: ("wagtail.blocks.StreamBlock", [[("poll_choice", 6)]], {}),
                },
            ),
        ),
    ]
