# Generated by Django 6.0.2 on 2026-06-09 17:24

import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("pages", "0003_alter_postpage_content"),
    ]

    operations = [
        migrations.AlterField(
            model_name="postpage",
            name="content",
            field=wagtail.fields.StreamField(
                [
                    ("rich_text", 0),
                    ("blog", 1),
                    ("news", 1),
                    ("url", 2),
                    ("video", 3),
                    ("poll", 5),
                ],
                block_lookup={
                    0: ("wagtail.blocks.RichTextBlock", (), {}),
                    1: ("wagtailmarkdown.blocks.MarkdownBlock", (), {}),
                    2: ("wagtail.blocks.URLBlock", (), {}),
                    3: ("wagtail.embeds.blocks.EmbedBlock", (), {"label": "Video"}),
                    4: ("wagtail.blocks.CharBlock", (), {"max_length": 200}),
                    5: ("wagtail.blocks.StreamBlock", [[("poll_choice", 4)]], {}),
                },
            ),
        ),
    ]
