# Generated by Django 6.0.2 on 2026-07-29 23:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("pages", "0004_alter_postpage_content"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="postindexpage",
            name="tags",
        ),
        migrations.RemoveField(
            model_name="postpage",
            name="tags",
        ),
        migrations.RemoveField(
            model_name="routablehomepage",
            name="tags",
        ),
    ]
