# Generated by Django 6.0.2 on 2026-02-24 21:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pages", "0004_postpage_image"),
    ]

    operations = [
        migrations.AddField(
            model_name="postpage",
            name="summary",
            field=models.TextField(
                blank=True,
                default="",
                help_text="AI generated summary. Delete to regenerate.",
            ),
        ),
    ]
