# Generated by Django 6.0.2 on 2026-07-29 23:46

import django.db.models.deletion
import modelcluster.contrib.taggit
import modelcluster.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("pages", "0005_remove_postindexpage_tags_remove_postpage_tags_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="postpage",
            name="tags",
            field=modelcluster.contrib.taggit.ClusterTaggableManager(
                blank=True,
                help_text="A comma-separated list of tags.",
                through="pages.TaggedContent",
                to="pages.ContentTag",
                verbose_name="Tags",
            ),
        ),
        migrations.AlterField(
            model_name="taggedcontent",
            name="content_object",
            field=modelcluster.fields.ParentalKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="tagged_items",
                to="pages.postpage",
            ),
        ),
    ]
