# Generated by Django 6.0.2 on 2026-08-26 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pages", "0006_create_legal_pages"),
    ]

    operations = [
        migrations.AddField(
            model_name="postpage",
            name="page_views",
            field=models.PositiveIntegerField(default=0),
        ),
    ]
