# Generated by Django 6.0.7 on 2026-08-27 20:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("pages", "0006_create_legal_pages"),
        ("pages", "0006_postpage_tags_alter_taggedcontent_content_object"),
    ]

    operations = []
