# Generated by Django 6.0.7 on 2026-08-28 16:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("pages", "0007_merge_20260827_2006"),
        ("pages", "0007_postpage_page_views"),
    ]

    operations = []
