# Generated by Django 6.0.7 on 2026-09-08 16:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("pages", "0008_merge_20260828_1620"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="legalpage",
            name="tags",
        ),
    ]
