# Generated by Django 6.0.7 on 2026-09-09 18:44

import django.db.models.deletion
import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pages", "0009_remove_legalpage_tags"),
        ("wagtailimages", "0027_image_description"),
    ]

    operations = [
        migrations.AddField(
            model_name="legalpage",
            name="image",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="wagtailimages.image",
                verbose_name="Image",
            ),
        ),
        migrations.AddField(
            model_name="legalpage",
            name="cards",
            field=wagtail.fields.StreamField(
                [("card", 3)],
                blank=True,
                block_lookup={
                    0: ("wagtail.blocks.CharBlock", (), {"required": True}),
                    1: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "choices": [
                                ("lightbulb", "Lightbulb"),
                                ("building-community", "Building Community"),
                                ("external-link", "External Link"),
                                ("warning-box", "Warning Box"),
                                ("repeat", "Repeat"),
                                ("user", "User"),
                                ("close", "Close"),
                                ("mail", "Mail"),
                                ("view-list", "View List"),
                                ("reload", "Reload"),
                                ("cookie", "Cookie"),
                                ("chart-bar", "Chart Bar"),
                                ("question-mark", "Question Mark"),
                            ]
                        },
                    ),
                    2: ("wagtail.blocks.RichTextBlock", (), {"required": True}),
                    3: (
                        "wagtail.blocks.StructBlock",
                        [[("title", 0), ("icon", 1), ("content", 2)]],
                        {},
                    ),
                },
                null=True,
            ),
        ),
    ]
