# Generated by Django 4.2.24 on 2025-10-08 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="CapturedEmail",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("email", models.EmailField(max_length=254)),
                ("referrer", models.CharField(blank=True, default="")),
                ("page_slug", models.CharField(blank=True, default="")),
            ],
        ),
    ]
