# Generated by Django 5.2.7 on 2025-11-04 22:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("marketing", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="capturedemail",
            name="address_city",
            field=models.CharField(blank=True, default=""),
        ),
        migrations.AddField(
            model_name="capturedemail",
            name="address_country",
            field=models.CharField(blank=True, default=""),
        ),
        migrations.AddField(
            model_name="capturedemail",
            name="address_state",
            field=models.CharField(blank=True, default=""),
        ),
        migrations.AddField(
            model_name="capturedemail",
            name="company",
            field=models.CharField(blank=True, default=""),
        ),
        migrations.AddField(
            model_name="capturedemail",
            name="first_name",
            field=models.CharField(blank=True, default=""),
        ),
        migrations.AddField(
            model_name="capturedemail",
            name="last_name",
            field=models.CharField(blank=True, default=""),
        ),
        migrations.AddField(
            model_name="capturedemail",
            name="mi",
            field=models.CharField(blank=True, default="", verbose_name="M.I."),
        ),
        migrations.AddField(
            model_name="capturedemail",
            name="opted_out",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="capturedemail",
            name="title",
            field=models.CharField(blank=True, default=""),
        ),
    ]
