# Generated by Django 5.2.8 on 2025-11-17 21:27

import django.db.models.deletion
import django.utils.timezone
import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("marketing", "0001_initial"),
        ("wagtailcore", "0095_groupsitepermission"),
    ]

    operations = [
        migrations.CreateModel(
            name="DetailPage",
            fields=[
                (
                    "page_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="wagtailcore.page",
                    ),
                ),
                (
                    "email_capture_intro",
                    models.TextField(
                        default="Drop your email below to get engineering updates."
                    ),
                ),
                (
                    "privacy_blurb",
                    models.TextField(
                        default="Privacy: no spam, one step unsubscribe. We'll only send high-signal dev content re this and other Boost libraries."
                    ),
                ),
                (
                    "body",
                    wagtail.fields.StreamField(
                        [("rich", 0), ("md", 1)],
                        blank=True,
                        block_lookup={
                            0: (
                                "wagtail.blocks.RichTextBlock",
                                (),
                                {
                                    "features": [
                                        "h1",
                                        "h2",
                                        "h3",
                                        "bold",
                                        "italic",
                                        "link",
                                        "ol",
                                        "ul",
                                        "code",
                                        "blockquote",
                                    ],
                                    "label": "Rich text",
                                },
                            ),
                            1: (
                                "wagtailmarkdown.blocks.MarkdownBlock",
                                (),
                                {"label": "Markdown"},
                            ),
                        },
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
            bases=("wagtailcore.page",),
        ),
        migrations.CreateModel(
            name="OutreachHomePage",
            fields=[
                (
                    "page_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="wagtailcore.page",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
            bases=("wagtailcore.page",),
        ),
        migrations.CreateModel(
            name="ProgramPage",
            fields=[
                (
                    "page_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="wagtailcore.page",
                    ),
                ),
                (
                    "email_capture_intro",
                    models.TextField(
                        default="Drop your email below to get engineering updates."
                    ),
                ),
                (
                    "privacy_blurb",
                    models.TextField(
                        default="Privacy: no spam, one step unsubscribe. We'll only send high-signal dev content re this and other Boost libraries."
                    ),
                ),
                (
                    "body",
                    wagtail.fields.StreamField(
                        [("rich", 0), ("md", 1)],
                        blank=True,
                        block_lookup={
                            0: (
                                "wagtail.blocks.RichTextBlock",
                                (),
                                {
                                    "features": [
                                        "h1",
                                        "h2",
                                        "h3",
                                        "bold",
                                        "italic",
                                        "link",
                                        "ol",
                                        "ul",
                                        "code",
                                        "blockquote",
                                    ],
                                    "label": "Rich text",
                                },
                            ),
                            1: (
                                "wagtailmarkdown.blocks.MarkdownBlock",
                                (),
                                {"label": "Markdown"},
                            ),
                        },
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
            bases=("wagtailcore.page",),
        ),
        migrations.CreateModel(
            name="ProgramPageIndex",
            fields=[
                (
                    "page_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="wagtailcore.page",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
            bases=("wagtailcore.page",),
        ),
        migrations.CreateModel(
            name="TopicPage",
            fields=[
                (
                    "page_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="wagtailcore.page",
                    ),
                ),
            ],
            options={
                "verbose_name": "Topic",
            },
            bases=("wagtailcore.page",),
        ),
        migrations.RemoveField(
            model_name="capturedemail",
            name="page_slug",
        ),
        migrations.AddField(
            model_name="capturedemail",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="capturedemail",
            name="page",
            field=models.ForeignKey(
                blank=True,
                default=None,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="captured_emails",
                to="wagtailcore.page",
            ),
        ),
    ]
