# Generated by Django 6.0.2 on 2026-03-06 01:57

from django.db import migrations, models


def delete_blank_emails(apps, schema_editor):
    CapturedEmail = apps.get_model("marketing", "CapturedEmail")
    count, _ = CapturedEmail.objects.filter(email="").delete()
    if count:
        print(f"\n  Deleted {count} CapturedEmail record(s) with blank email.")


class Migration(migrations.Migration):

    dependencies = [
        ("marketing", "0003_capturedemail_address_city_and_more"),
        ("wagtailcore", "0096_referenceindex_referenceindex_source_object_and_more"),
    ]

    operations = [
        migrations.RunPython(delete_blank_emails, migrations.RunPython.noop),
        migrations.AddField(
            model_name="capturedemail",
            name="github_username",
            field=models.CharField(blank=True, default=""),
        ),
        migrations.AddConstraint(
            model_name="capturedemail",
            constraint=models.CheckConstraint(
                condition=models.Q(("email", ""), _negated=True),
                name="captured_email_requires_email",
            ),
        ),
    ]
