# Generated by Django 5.2.8 on 2026-02-13 14:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("libraries", "0037_library_tier"),
        ("versions", "0026_alter_versionfile_operating_system"),
    ]

    operations = [
        migrations.CreateModel(
            name="LibraryPatch",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "patch_name",
                    models.CharField(
                        help_text="A descriptive name of this patch. Also used to generate the slug for the patch page.",
                        max_length=256,
                        unique=True,
                    ),
                ),
                (
                    "patch_file",
                    models.FileField(
                        help_text="Patch File generated from the patch diff.",
                        upload_to="",
                    ),
                ),
                (
                    "library",
                    models.ForeignKey(
                        blank=True,
                        help_text="Library that this Patch applies to. May be null if this patch is not specific to a library.",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="libraries.library",
                    ),
                ),
                (
                    "version",
                    models.ForeignKey(
                        help_text="Version of Boost that this patch applies to.",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="versions.version",
                    ),
                ),
            ],
        ),
    ]
