# Generated by Django 5.2.8 on 2026-02-12 18:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("libraries", "0037_library_tier"),
    ]

    operations = [
        migrations.CreateModel(
            name="LibraryPatch",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "patch_name",
                    models.CharField(
                        help_text="A descriptive name of this patch. Also used to generate the slug for the patch page.",
                        max_length=256,
                        unique=True,
                    ),
                ),
                (
                    "patch_file",
                    models.FileField(
                        help_text="Patch File generated from the patch diff.",
                        upload_to="",
                    ),
                ),
                (
                    "library_version",
                    models.ForeignKey(
                        help_text="Library version that this patch applies to. Will be used to sort and display this patch.",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="libraries.libraryversion",
                    ),
                ),
            ],
        ),
    ]
