apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: boost
spec:
  minReplicas: 2
  maxReplicas: 8
  metrics:
  - resource:
      name: cpu
      target:
        averageUtilization: 50
        type: Utilization
    type: Resource
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: boost
