# Generated by Django 6.0.2 on 2026-03-06 16:28

import core.validators
import django.db.models.deletion
import django.utils.timezone
import wagtail.fields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("wagtailcore", "0096_referenceindex_referenceindex_source_object_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="BlogIndexPage",
            fields=[
                (
                    "page_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="wagtailcore.page",
                    ),
                ),
            ],
            options={
                "verbose_name": "Blog index",
                "verbose_name_plural": "Blog indices",
            },
            bases=("wagtailcore.page",),
        ),
        migrations.CreateModel(
            name="BlogPostPage",
            fields=[
                (
                    "page_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="wagtailcore.page",
                    ),
                ),
                (
                    "body",
                    wagtail.fields.StreamField(
                        [("rich_text", 0)],
                        blank=True,
                        block_lookup={
                            0: (
                                "wagtail.blocks.RichTextBlock",
                                (),
                                {
                                    "features": [
                                        "h1",
                                        "h2",
                                        "h3",
                                        "bold",
                                        "italic",
                                        "link",
                                        "ol",
                                        "ul",
                                        "code",
                                        "blockquote",
                                    ],
                                    "label": "Body",
                                },
                            )
                        },
                    ),
                ),
                ("publish_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("excerpt", models.CharField(blank=True, default="", max_length=256)),
                (
                    "image",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="blog/%Y/%m/",
                        validators=[
                            core.validators.FileTypeValidator(
                                extensions=[".jpg", ".jpeg", ".png"]
                            ),
                            core.validators.MaxFileSizeValidator(max_size=1048576),
                        ],
                    ),
                ),
                (
                    "author",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="blog_posts",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Blog post",
                "verbose_name_plural": "Blog posts",
            },
            bases=("wagtailcore.page",),
        ),
    ]
