# Generated by Django 4.2.16 on 2024-11-05 23:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("slack", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="slackuser",
            name="image_48",
            field=models.URLField(default=""),
            preserve_default=False,
        ),
    ]
