# Generated by Django 5.2.8 on 2026-01-20 18:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("slack", "0002_thread_last_update_as_datetime"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="thread",
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name="thread",
            name="channel",
        ),
        migrations.AlterUniqueTogether(
            name="seenmessage",
            unique_together=set(),
        ),
        migrations.AddField(
            model_name="channel",
            name="channel_created_ts",
            field=models.CharField(max_length=32, null=True),
        ),
        migrations.AddField(
            model_name="seenmessage",
            name="message_time",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="seenmessage",
            name="user",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="slack.slackuser",
            ),
        ),
        migrations.DeleteModel(
            name="ChannelUpdateGap",
        ),
        migrations.RemoveField(
            model_name="seenmessage",
            name="thread",
        ),
        migrations.DeleteModel(
            name="Thread",
        ),
    ]
