# Generated by Django 6.0.2 on 2026-02-10 16:51

import django.db.models.deletion
import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("wagtailcore", "0096_referenceindex_referenceindex_source_object_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Testimonial",
            fields=[
                (
                    "page_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="wagtailcore.page",
                    ),
                ),
                ("author", models.CharField(max_length=255)),
                (
                    "author_slug",
                    models.SlugField(
                        help_text="Slug used for author's URL - must be unique",
                        unique=True,
                    ),
                ),
                (
                    "pull_quote",
                    models.TextField(
                        blank=True,
                        default="",
                        help_text="Short extract from the full body",
                    ),
                ),
                (
                    "body",
                    wagtail.fields.StreamField(
                        [("rich", 0), ("md", 1)],
                        blank=True,
                        block_lookup={
                            0: (
                                "wagtail.blocks.RichTextBlock",
                                (),
                                {
                                    "features": [
                                        "h1",
                                        "h2",
                                        "h3",
                                        "bold",
                                        "italic",
                                        "link",
                                        "ol",
                                        "ul",
                                        "code",
                                        "blockquote",
                                    ],
                                    "label": "Rich text",
                                },
                            ),
                            1: (
                                "wagtailmarkdown.blocks.MarkdownBlock",
                                (),
                                {"label": "Markdown"},
                            ),
                        },
                    ),
                ),
            ],
            options={
                "verbose_name": "Testimonial",
                "verbose_name_plural": "Testimonials",
            },
            bases=("wagtailcore.page",),
        ),
        migrations.CreateModel(
            name="TestimonialsIndexPage",
            fields=[
                (
                    "page_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="wagtailcore.page",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
            bases=("wagtailcore.page",),
        ),
    ]
