# Generated by Django 6.0.2 on 2026-05-27 23:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("testimonials", "0001_initial"),
        ("wagtailimages", "0027_image_description"),
    ]

    operations = [
        migrations.AddField(
            model_name="testimonial",
            name="author_avatar",
            field=models.ForeignKey(
                blank=True,
                help_text="Optional author avatar shown on the homepage card",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="wagtailimages.image",
            ),
        ),
        migrations.AddField(
            model_name="testimonial",
            name="author_role",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Optional role/affiliation shown under the author's name",
                max_length=255,
            ),
        ),
    ]
