# Generated by Django 6.0.2 on 2026-02-10 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("testimonials", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="testimonial",
            name="author_url",
            field=models.URLField(
                blank=True,
                default="",
                help_text="Optional URL to link the author's name to",
            ),
        ),
    ]
