# Generated by Django 6.0.2 on 2026-06-02 21:29

import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("testimonials", "0002_testimonial_author_avatar_testimonial_author_role"),
    ]

    operations = [
        migrations.AlterField(
            model_name="testimonial",
            name="author_role",
            field=wagtail.fields.RichTextField(
                blank=True,
                default="",
                help_text="Optional role/affiliation shown under the author's name. Supports hyperlinks.",
            ),
        ),
    ]
