# Generated by Django 6.0.2 on 2026-02-10 17:57

import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("testimonials", "0002_testimonial_author_url"),
    ]

    operations = [
        migrations.AddField(
            model_name="testimonial",
            name="author_tagline",
            field=wagtail.fields.StreamField(
                [("md", 0)],
                blank=True,
                block_lookup={
                    0: (
                        "wagtailmarkdown.blocks.MarkdownBlock",
                        (),
                        {"label": "Markdown"},
                    )
                },
            ),
        ),
    ]
