# Generated by Django 5.2.8 on 2025-11-20 22:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Badge",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200, verbose_name="title")),
                (
                    "display_name",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="display name"
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True,
                        help_text="Description of what this badge represents",
                        verbose_name="description",
                    ),
                ),
                (
                    "calculator_class_reference",
                    models.CharField(
                        help_text="lookup field for class_reference in badge Calculator implementations",
                        max_length=255,
                        unique=True,
                        verbose_name="calculator class reference",
                    ),
                ),
                (
                    "image_light",
                    models.CharField(
                        help_text="Path to badge image for light mode in static directory",
                        max_length=255,
                        verbose_name="image path (light mode)",
                    ),
                ),
                (
                    "image_dark",
                    models.CharField(
                        help_text="Path to badge image for dark mode in static directory",
                        max_length=255,
                        verbose_name="image path (dark mode)",
                    ),
                ),
                (
                    "image_small_light",
                    models.CharField(
                        help_text="Path to small badge image for light mode in static directory",
                        max_length=255,
                        verbose_name="small image path (light mode)",
                    ),
                ),
                (
                    "image_small_dark",
                    models.CharField(
                        help_text="Path to small badge image for dark mode in static directory",
                        max_length=255,
                        verbose_name="small image path (dark mode)",
                    ),
                ),
                ("is_nft_enabled", models.BooleanField(default=False)),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("updated", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["calculator_class_reference"],
            },
        ),
        migrations.CreateModel(
            name="UserBadge",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "grade",
                    models.IntegerField(
                        blank=True,
                        help_text="Grade or level of this badge for the user",
                        null=True,
                    ),
                ),
                ("approved", models.BooleanField(default=False)),
                ("nft_minted", models.BooleanField(default=False)),
                ("nft_transfer_url", models.TextField(blank=True, null=True)),
                (
                    "unclaimed",
                    models.BooleanField(
                        default=False,
                        help_text="Default false, true when badge is_nft_enabled=True",
                    ),
                ),
                (
                    "published",
                    models.BooleanField(
                        default=False, help_text="Visible on the user's profile"
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("updated", models.DateTimeField(auto_now=True)),
                (
                    "badge",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="user_badges",
                        to="badges.badge",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="user_badges",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created"],
                "unique_together": {("user", "badge")},
            },
        ),
    ]
