# Generated by Django 6.0.2 on 2026-08-03 20:27

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("contenttypes", "0002_remove_content_type_name"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Achievement",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255, verbose_name="name")),
                (
                    "slug",
                    models.SlugField(max_length=255, unique=True, verbose_name="slug"),
                ),
                (
                    "description",
                    models.TextField(blank=True, verbose_name="description"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="created at"),
                ),
            ],
            options={
                "ordering": ("name",),
            },
        ),
        migrations.CreateModel(
            name="Badge",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "label",
                    models.CharField(
                        choices=[
                            ("library_author", "Library Author"),
                            ("version_author", "Version Author"),
                            ("commits_master", "Commits Master"),
                            ("reviewer", "Reviewer"),
                            ("maintainer", "Maintainer"),
                            ("documenter", "Documenter"),
                            ("regular", "Regular"),
                            ("publisher", "Publisher"),
                        ],
                        max_length=50,
                        unique=True,
                        verbose_name="label",
                    ),
                ),
                (
                    "description",
                    models.TextField(blank=True, verbose_name="description"),
                ),
                (
                    "achievement",
                    models.ForeignKey(
                        help_text="Which achievement type feeds this badge.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="badges",
                        to="badges.achievement",
                    ),
                ),
            ],
            options={
                "ordering": ("label",),
            },
        ),
        migrations.CreateModel(
            name="BadgeTier",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "rank",
                    models.CharField(
                        choices=[
                            ("bronze", "Bronze"),
                            ("silver", "Silver"),
                            ("gold", "Gold"),
                            ("platinum", "Platinum"),
                            ("diamond", "Diamond"),
                        ],
                        max_length=20,
                        verbose_name="rank",
                    ),
                ),
                (
                    "threshold",
                    models.PositiveIntegerField(
                        help_text="Number of valid achievements required to reach this rank. Changing it applies to new earners only: members who already reached the old threshold keep their badge.",
                        verbose_name="threshold",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Retired tiers stop awarding badges but keep their history, including the badges already earned against them.",
                        verbose_name="active",
                    ),
                ),
                (
                    "deactivated_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="deactivated at"
                    ),
                ),
                (
                    "badge",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tiers",
                        to="badges.badge",
                    ),
                ),
                (
                    "deactivated_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="Admin who deactivated this tier.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ("threshold",),
            },
        ),
        migrations.CreateModel(
            name="UserAchievement",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="created at"),
                ),
                (
                    "is_valid",
                    models.BooleanField(default=True, verbose_name="is valid"),
                ),
                (
                    "invalidated_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="invalidated at"
                    ),
                ),
                (
                    "invalidation_notes",
                    models.TextField(blank=True, verbose_name="invalidation notes"),
                ),
                (
                    "source_type",
                    models.CharField(
                        choices=[("automatic", "Automatic"), ("manual", "Manual")],
                        default="automatic",
                        max_length=20,
                        verbose_name="source type",
                    ),
                ),
                (
                    "source_object_id",
                    models.PositiveBigIntegerField(blank=True, null=True),
                ),
                (
                    "grant_notes",
                    models.TextField(
                        blank=True,
                        help_text="For manual grants: why this was granted by hand.",
                        verbose_name="grant notes",
                    ),
                ),
                (
                    "achievement",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="user_achievements",
                        to="badges.achievement",
                    ),
                ),
                (
                    "granted_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="For manual grants: the admin who created this achievement.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "invalidated_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="Admin who invalidated this achievement.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "source_content_type",
                    models.ForeignKey(
                        blank=True,
                        help_text="For automatic grants: the model that triggered the grant.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="contenttypes.contenttype",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="achievements",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ("-created_at",),
            },
        ),
        migrations.CreateModel(
            name="UserBadge",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "awarded_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="awarded at"
                    ),
                ),
                (
                    "revoked_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="revoked at"
                    ),
                ),
                (
                    "revocation_notes",
                    models.TextField(blank=True, verbose_name="revocation notes"),
                ),
                (
                    "revocation_source",
                    models.CharField(
                        blank=True,
                        choices=[("cascade", "Cascade"), ("manual", "Manual")],
                        default="",
                        help_text="Manual revocations are not re-earned automatically; cascade revocations are, once the achievement count recovers.",
                        max_length=20,
                        verbose_name="revocation source",
                    ),
                ),
                (
                    "count_at_revocation",
                    models.PositiveIntegerField(
                        blank=True,
                        help_text="Valid achievement count at the moment of revocation.",
                        null=True,
                        verbose_name="count at revocation",
                    ),
                ),
                (
                    "badge",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="user_badges",
                        to="badges.badge",
                    ),
                ),
                (
                    "revoked_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="Admin who revoked this badge.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "tier",
                    models.ForeignKey(
                        help_text="The tier that justified this badge. A tier with badges awarded against it cannot be hard-deleted.",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="user_badges",
                        to="badges.badgetier",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="badges",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ("-awarded_at",),
            },
        ),
        migrations.AddConstraint(
            model_name="badgetier",
            constraint=models.UniqueConstraint(
                condition=models.Q(("is_active", True)),
                fields=("badge", "rank"),
                name="unique_active_badgetier_per_rank",
            ),
        ),
        migrations.AddConstraint(
            model_name="userachievement",
            constraint=models.UniqueConstraint(
                condition=models.Q(("source_type", "automatic")),
                fields=(
                    "user",
                    "achievement",
                    "source_content_type",
                    "source_object_id",
                ),
                name="unique_automatic_user_achievement_source",
            ),
        ),
        migrations.AddConstraint(
            model_name="userbadge",
            constraint=models.UniqueConstraint(
                fields=("badge", "user", "tier"), name="unique_user_badge_tier"
            ),
        ),
    ]
