# Generated by Django 6.0.2 on 2026-08-03 20:44

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("badges", "0002_seed_achievements_and_badges"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="AchievementSyncRun",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "source_slug",
                    models.CharField(max_length=255, verbose_name="source slug"),
                ),
                (
                    "mode",
                    models.CharField(
                        choices=[("backfill", "Backfill"), ("reconcile", "Reconcile")],
                        max_length=20,
                        verbose_name="mode",
                    ),
                ),
                (
                    "trigger",
                    models.CharField(
                        choices=[
                            ("command", "Command"),
                            ("admin", "Admin"),
                            ("pipeline", "Release pipeline"),
                        ],
                        default="command",
                        max_length=20,
                        verbose_name="trigger",
                    ),
                ),
                (
                    "started_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="started at"
                    ),
                ),
                (
                    "finished_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="finished at"
                    ),
                ),
                (
                    "added",
                    models.PositiveIntegerField(default=0, verbose_name="grants added"),
                ),
                (
                    "removed",
                    models.PositiveIntegerField(
                        default=0, verbose_name="grants removed"
                    ),
                ),
                (
                    "members_changed",
                    models.PositiveIntegerField(
                        default=0, verbose_name="members changed"
                    ),
                ),
                (
                    "refused",
                    models.BooleanField(
                        default=False,
                        help_text="The source yielded nothing, so stale grants were left alone.",
                        verbose_name="refused",
                    ),
                ),
                (
                    "error",
                    models.TextField(
                        blank=True,
                        help_text="What the run raised, where it did not finish. Deletions are chunked rather than wrapped in one transaction, so a run that died part way left the grants it had already removed removed.",
                        verbose_name="error",
                    ),
                ),
                (
                    "triggered_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="The admin who started this run, where a person started it.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "achievement sync run",
                "ordering": ("-started_at",),
            },
        ),
    ]
