# Generated by Django 6.0.2 on 2026-08-19 14:21

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("badges", "0003_achievementsyncrun"),
        ("contenttypes", "0002_remove_content_type_name"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="userachievement",
            name="unique_automatic_user_achievement_source",
        ),
        migrations.AddField(
            model_name="userachievement",
            name="dedup_info",
            field=models.TextField(
                blank=True,
                help_text="For automatic grants: the source's stable id for the evidence.",
                null=True,
                verbose_name="dedup info",
            ),
        ),
        migrations.AddConstraint(
            model_name="userachievement",
            constraint=models.UniqueConstraint(
                condition=models.Q(
                    ("dedup_info__isnull", False), ("source_type", "automatic")
                ),
                fields=("user", "achievement", "dedup_info"),
                name="unique_automatic_user_achievement_dedup",
            ),
        ),
    ]
